In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import datetime
import numpy as np
from sodapy import Socrata
from app_token import app_token
from pgconnect import pgconnect

In [3]:
import json
import psycopg2

In [4]:
from sqlalchemy import create_engine

### POSTGRES CONNECTION

In [6]:
db = pgconnect['db']
host = pgconnect['host']
user = pgconnect['user']

In [7]:
# sqlalchemy engine for using .to_sql
url = f"postgres+psycopg2://{user}:@{host}:5432/{db}"
engine = create_engine(url)

In [9]:
con = psycopg2.connect(database=db,host=host,user=user)
cur = con.cursor()

In [10]:
### write the uof_filenum table
cur.execute(open('create_uof_filenum.sql').read())
con.commit() # commit the create statement to the database

In [4]:
# columns for uof_filenum table
table_cols = ['objectid',
'zip',
'filenum',
'occurred_d',
'occurred_t',
'current_ba',
'offsex',
'offrace',
'hire_dt',
'off_injure',
'offcondtyp',
'off_hospit',
'service_ty',
'uof_reason',
'cycles_num',
'street_n',
'street',
'street_g',
'street_t',
'address',
'citnum',
'citrace',
'citsex',
'cit_injure',
'citcondtyp',
'cit_arrest',
'cit_infl_a',
'citcharget',
'council_district',
'ra',
'beat',
'sector',
'division',
'x',
'y',
'geocoded_column',
'year_reported']

### API

In [5]:
limit = 6000

In [6]:
client = Socrata("www.dallasopendata.com", app_token=app_token['token'])

In [7]:
url_dict = dict (
    data_2019 ='46zb-7qgj',
    data_2018 ='33un-ry4j',
    data_2017 ='tsu5-ca6k',
    data_2016 ='99fn-pvaf',
    data_2015 ='594v-2cnd',
    data_2014 ='xiv3-e8g7',
    data_2013 ='6gnu-avpf'
    )

### Processing the files in this order is essential to not corrupting the data by copying down values to empty cells

In [15]:
df_2019 = pd.DataFrame(client.get(url_dict['data_2019'], limit=limit))

In [16]:
df_2019.head(30)

,objectid,zip,filenum,uofnum,occurred_d,occurred_t,current_ba,offsex,offrace,hire_dt,...,council_district,ra,beat,sector,division,x,y,geocoded_column,:@computed_region_sjyw_rtbm,:@computed_region_2f7u_b5gs
0,2817,75253,UF2019-1702,"62295, 63542",2019-12-01T00:00:00.000,10:34 PM,11285,Male,White,2017-03-08T00:00:00.000,...,D8,6062,357,350,SOUTHEAST,2557123.437,6944231.397,"{'type': 'Point', 'coordinates': [-96.586265, ...",8,3
1,2234,75208,UF2019-1344,61093,2019-10-06T00:00:00.000,12:50 AM,11208,Male,White,2016-08-24T00:00:00.000,...,D1,4160,444,440,SOUTHWEST,2474936.793,6952151.398,"{'type': 'Point', 'coordinates': [-96.853036, ...",1,3
2,2755,75231,UF2019-1665,62820,2019-12-31T00:00:00.000,11:37 PM,9415,Male,White,2008-04-02T00:00:00.000,...,D9,6034,247,240,NORTHEAST,2508349.267,7001784.466,"{'type': 'Point', 'coordinates': [-96.741661, ...",13,3
3,2110,75228,UF2019-1314,60990,2019-09-30T00:00:00.000,6:20 PM,9884,Male,Hispanic,2009-06-10T00:00:00.000,...,D9,1132,228,220,NORTHEAST,2536678.324,6999039.025,"{'type': 'Point', 'coordinates': [-96.649175, ...",13,3
4,1663,75051,UF2019-1030,"59592, 59600",2019-08-04T00:00:00.000,12:10 AM,10480,Male,Hispanic,2012-09-26T00:00:00.000,...,NaN,NaN,NaN,NaN,NaN,2433285.622,6953645.72,"{'type': 'Point', 'coordinates': [-96.98722, 3...",NaN,NaN
5,2538,75217,UF2019-1539,62255,2019-11-20T00:00:00.000,12:30 AM,9697,Male,White,2008-12-10T00:00:00.000,...,D5,2196,331,330,SOUTHEAST,2518664.313,6949657.426,"{'type': 'Point', 'coordinates': [-96.710924, ...",5,3
6,1966,75214,UF2019-1218,60444,2019-09-11T00:00:00.000,12:43 AM,10431,Male,White,2012-06-20T00:00:00.000,...,D2,1171,111,110,CENTRAL,2511580.252,6981361.061,"{'type': 'Point', 'coordinates': [-96.732593, ...",12,3
7,515,75204,UF2019-0338,55835,2019-03-11T00:00:00.000,3:50 AM,11278,Male,White,2017-02-08T00:00:00.000,...,D14,2017,155,150,CENTRAL,2494741.403,6978419.971,"{'type': 'Point', 'coordinates': [-96.787302, ...",12,3
8,1768,75201,UF2019-1096,58582,2019-06-23T00:00:00.000,7:50 PM,11233,Male,White,2016-11-02T00:00:00.000,...,D14,2062,134,130,CENTRAL,2491108.139,6971148.627,"{'type': 'Point', 'coordinates': [-96.799308, ...",12,3
9,72,75207,UF2019-0045,54460,2019-01-07T00:00:00.000,8:15 PM,9770,Male,White,2009-03-18T00:00:00.000,...,D6,6067,514,510,NORTHWEST,2476175.336,6981696.717,"{'type': 'Point', 'coordinates': [-96.846541, ...",2,3
10,1560,75208,UF2019-0969,59198,2019-07-18T00:00:00.000,11:56 AM,7855,Male,White,2000-01-07T00:00:00.000,...,D1,4140,417,410,SOUTHWEST,2480033.001,6956627.779,"{'type': 'Point', 'coordinates': [-96.836611, ...",1,3
11,1090,75216,UF2019-0704,57406,2019-05-10T00:00:00.000,1:00 PM,8645,Female,Black,2005-05-20T00:00:00.000,...,D4,4322,727,720,SOUTH CENTRAL,2489283.104,6937390.895,"{'type': 'Point', 'coordinates': [-96.806984, ...",4,3
12,1720,75202,UF2019-1068,59914,2019-08-16T00:00:00.000,8:43 PM,9000,Male,Hispanic,2006-11-15T00:00:00.000,...,D14,2061,133,130,CENTRAL,2490893.402,6971091.929,NaN,NaN,NaN
13,1984,75287,UF2019-1230,"60932, 60933, 60934",2019-09-28T00:00:00.000,5:35 PM,11368,Male,White,2017-07-26T00:00:00.000,...,D12,6059,613,610,NORTH CENTRAL,2475207.802,7046629.116,"{'type': 'Point', 'coordinates': [-96.846143, ...",14,3
14,2697,75216,UF2019-1633,61954,2019-11-16T00:00:00.000,12:55 AM,11509,Male,White,2018-05-02T00:00:00.000,...,D4,4322,727,720,SOUTH CENTRAL,2489283.104,6937390.895,"{'type': 'Point', 'coordinates': [-96.806984, ...",4,3
15,207,75252,UF2019-0124,55013,2019-01-28T00:00:00.000,12:30 PM,7061,Male,White,1994-07-05T00:00:00.000,...,D12,4422,621,620,NORTH CENTRAL,2491016.32,7053489.902,"{'type': 'Point', 'coordinates': [-96.795404, ...",14,3
16,1061,75212,UF2019-0686,55214,2019-02-09T00:00:00.000,10:35 PM,11425,Female,White,2017-11-29T00:00:00.000,...,D6,4038,423,420,SOUTHWEST,2474994.422,6971621.374,"{'type': 'Point', 'coordinates': [-96.852421, ...",6,3
17,800,75236,UF2019-0521,57246,2019-05-05T00:00:00.000,5:00 PM,9572,Male,White,2008-08-20T00:00:00.000,...,D3,4401,435,430,SOUTHWEST,2447982.265,6930266.477,NaN,NaN,NaN
18,2367,75202,UF2019-1427,60139,2019-08-29T00:00:00.000,8:40 PM,9881,Male,White,2009-06-10T00:00:00.000,...,D14,2071,133,130,CENTRAL,2489689.079,6970448.413,"{'type': 'Point', 'coordinates': [-96.803969, ...",12,3
19,975,75228,UF2019-0627,57695,2019-05-20T00:00:00.000,11:20 PM,9675,Male,White,2008-12-10T00:00:00.000,...,D9,1132,228,220,NORTHEAST,2536678.324,6999039.025,"{'type': 'Point', 'coordinates': [-96.649175, ...",13,3
20,1025,75208,UF2019-0660,58573,2019-03-31T00:00:00.000,9:20 PM,11241,Female,White,2016-11-30T00:00:00.000,...,D1,4141,446,440,SOUTHWEST,2483587.416,6954879.596,"{'type': 'Point', 'coordinates': [-96.825104, ...",1,3
21,1786,75216,UF2019-1106,60054,2019-08-24T00:00:00.000,4:50 PM,11028,Male,White,2015-06-03T00:00:00.000,...,D4,4300,726,720,SOUTH CENTRAL,2497847.071,6943020.952,"{'type': 'Point', 'coordinates': [-96.778775, ...",4,3
22,337,75243,UF2019-0218,"55315, 55316",2019-02-16T00:00:00.000,4:50 PM,11306,Male,White,2017-04-05T00:00:00.000,...,NaN,NaN,NaN,NaN,NaN,2520679.891,7019315.305,"{'type': 'Point', 'coordinates': [-96.700482, ...",NaN,NaN
23,1771,75231,UF2019-1097,59482,2019-07-31T00:00:00.000,10:30 AM,8425,Male,White,2003-08-15T00:00:00.000,...,D13,6014,213,210,NORTHEAST,2507860.636,7002746.437,"{'type': 'Point', 'coordinates': [-96.743621, ...",11,3
24,409,75218,UF2019-0263,55780,2019-03-08T00:00:00.000,2:15 AM,9573,Male,Hispanic,2008-08-20T00:00:00.000,...,D9,1100,233,230,NORTHEAST,2526618.478,6998483.295,"{'type': 'Point', 'coordinates': [-96.681572, ...",13,3
25,1612,75218,UF2019-1000,"60461, 60462",2019-04-10T00:00:00.000,4:48 AM,11473,Female,White,2018-02-21T00:00:00.000,...,D9,1114,232,230,NORTHEAST,2525944.808,6996333.292,"{'type': 'Point', 'coordinates': [-96.684775, ...",13,3
26,296,75216,UF2019-0192,54821,2019-01-25T00:00:00.000,9:50 AM,10021,Male,White,2009-11-11T00:00:00.000,...,D4,4225,728,720,SOUTH CENTRAL,2497160.963,6947606.047,"{'type': 'Point', 'coordinates': [-96.780455, ...",4,3
27,42,75241,UF2019-0026,54270,2019-01-01T00:00:00.000,7:10 PM,11281,Male,Other,2017-02-22T00:00:00.000,...,D8,4326,735,730,SOUTH CENTRAL,2498243.117,6937364.104,"{'type': 'Point', 'coordinates': [-96.777632, ...",8,3
28,1243,75210,UF2019-0785,"57169, 57170",2019-05-02T00:00:00.000,6:15 PM,10695,Male,White,2013-11-06T00:00:00.000,...,D7,2150,313,310,SOUTHEAST,2509968.529,6965321.722,"{'type': 'Point', 'coordinates': [-96.738253, ...",7,3
29,1556,75212,UF2019-0968,59189,2019-07-18T00:00:00.000,8:15 PM,11039,Male,White,2015-06-17T00:00:00.000,...,D6,4012,422,420,SOUTHWEST,2472250.476,6973242.286,"{'type': 'Point', 'coordinates': [-96.860527, ...",6,3

In [17]:
# replace NaN string values with None type for proper load into database
df_2019.replace(to_replace='NaN',value=None,inplace=True)

objectid                       None
zip                            None
filenum                        None
uofnum                         None
occurred_d                     None
occurred_t                     None
current_ba                     None
offsex                         None
offrace                        None
hire_dt                        None
off_injure                     None
offcondtyp                     None
off_hospit                     None
service_ty                     None
forcetype                      None
uof_reason                     None
cycles_num                     None
forceeffec                     None
street_n                       None
street                         None
street_g                       None
street_t                       None
address                        None
citnum                         None
citrace                        None
citsex                         None
cit_injure                     None
citcondtyp                     None
cit_arrest                     None
cit_infl_a                     None
citcharget                     None
council_district               None
ra                             None
beat                           None
sector                         None
division                       None
x                              None
y                              None
geocoded_column                None
:@computed_region_sjyw_rtbm    None
:@computed_region_2f7u_b5gs    None
dtype: object

In [18]:
# cast all empty values into None type
df_2019.where(pd.notnull(df_2019),None,inplace=True)

In [19]:
# convert the geocode column from dict to JSON string for load into database
df_2019['geocoded_column'] = df_2019['geocoded_column'].apply(lambda x:json.dumps(x))

In [20]:
# replace NULL string values with None type for proper load into database
df_2019.replace(to_replace='NULL',inplace=True)

objectid                       None
zip                            None
filenum                        None
uofnum                         None
occurred_d                     None
occurred_t                     None
current_ba                     None
offsex                         None
offrace                        None
hire_dt                        None
off_injure                     None
offcondtyp                     None
off_hospit                     None
service_ty                     None
forcetype                      None
uof_reason                     None
cycles_num                     None
forceeffec                     None
street_n                       None
street                         None
street_g                       None
street_t                       None
address                        None
citnum                         None
citrace                        None
citsex                         None
cit_injure                     None
citcondtyp                     None
cit_arrest                     None
cit_infl_a                     None
citcharget                     None
council_district               None
ra                             None
beat                           None
sector                         None
division                       None
x                              None
y                              None
geocoded_column                None
:@computed_region_sjyw_rtbm    None
:@computed_region_2f7u_b5gs    None
dtype: object

In [21]:
# adding the year reported values
df_2019['year_reported'] = '2019'

In [22]:
df_2019.head(30)

,objectid,zip,filenum,uofnum,occurred_d,occurred_t,current_ba,offsex,offrace,hire_dt,...,ra,beat,sector,division,x,y,geocoded_column,:@computed_region_sjyw_rtbm,:@computed_region_2f7u_b5gs,year_reported
0,2817,75253,UF2019-1702,"62295, 63542",2019-12-01T00:00:00.000,10:34 PM,11285,Male,White,2017-03-08T00:00:00.000,...,6062,357,350,SOUTHEAST,2557123.437,6944231.397,"{""type"": ""Point"", ""coordinates"": [-96.586265, ...",8,3,2019
1,2234,75208,UF2019-1344,61093,2019-10-06T00:00:00.000,12:50 AM,11208,Male,White,2016-08-24T00:00:00.000,...,4160,444,440,SOUTHWEST,2474936.793,6952151.398,"{""type"": ""Point"", ""coordinates"": [-96.853036, ...",1,3,2019
2,2755,75231,UF2019-1665,62820,2019-12-31T00:00:00.000,11:37 PM,9415,Male,White,2008-04-02T00:00:00.000,...,6034,247,240,NORTHEAST,2508349.267,7001784.466,"{""type"": ""Point"", ""coordinates"": [-96.741661, ...",13,3,2019
3,2110,75228,UF2019-1314,60990,2019-09-30T00:00:00.000,6:20 PM,9884,Male,Hispanic,2009-06-10T00:00:00.000,...,1132,228,220,NORTHEAST,2536678.324,6999039.025,"{""type"": ""Point"", ""coordinates"": [-96.649175, ...",13,3,2019
4,1663,75051,UF2019-1030,"59592, 59600",2019-08-04T00:00:00.000,12:10 AM,10480,Male,Hispanic,2012-09-26T00:00:00.000,...,None,None,None,None,2433285.622,6953645.72,"{""type"": ""Point"", ""coordinates"": [-96.98722, 3...",None,None,2019
5,2538,75217,UF2019-1539,62255,2019-11-20T00:00:00.000,12:30 AM,9697,Male,White,2008-12-10T00:00:00.000,...,2196,331,330,SOUTHEAST,2518664.313,6949657.426,"{""type"": ""Point"", ""coordinates"": [-96.710924, ...",5,3,2019
6,1966,75214,UF2019-1218,60444,2019-09-11T00:00:00.000,12:43 AM,10431,Male,White,2012-06-20T00:00:00.000,...,1171,111,110,CENTRAL,2511580.252,6981361.061,"{""type"": ""Point"", ""coordinates"": [-96.732593, ...",12,3,2019
7,515,75204,UF2019-0338,55835,2019-03-11T00:00:00.000,3:50 AM,11278,Male,White,2017-02-08T00:00:00.000,...,2017,155,150,CENTRAL,2494741.403,6978419.971,"{""type"": ""Point"", ""coordinates"": [-96.787302, ...",12,3,2019
8,1768,75201,UF2019-1096,58582,2019-06-23T00:00:00.000,7:50 PM,11233,Male,White,2016-11-02T00:00:00.000,...,2062,134,130,CENTRAL,2491108.139,6971148.627,"{""type"": ""Point"", ""coordinates"": [-96.799308, ...",12,3,2019
9,72,75207,UF2019-0045,54460,2019-01-07T00:00:00.000,8:15 PM,9770,Male,White,2009-03-18T00:00:00.000,...,6067,514,510,NORTHWEST,2476175.336,6981696.717,"{""type"": ""Point"", ""coordinates"": [-96.846541, ...",2,3,2019
10,1560,75208,UF2019-0969,59198,2019-07-18T00:00:00.000,11:56 AM,7855,Male,White,2000-01-07T00:00:00.000,...,4140,417,410,SOUTHWEST,2480033.001,6956627.779,"{""type"": ""Point"", ""coordinates"": [-96.836611, ...",1,3,2019
11,1090,75216,UF2019-0704,57406,2019-05-10T00:00:00.000,1:00 PM,8645,Female,Black,2005-05-20T00:00:00.000,...,4322,727,720,SOUTH CENTRAL,2489283.104,6937390.895,"{""type"": ""Point"", ""coordinates"": [-96.806984, ...",4,3,2019
12,1720,75202,UF2019-1068,59914,2019-08-16T00:00:00.000,8:43 PM,9000,Male,Hispanic,2006-11-15T00:00:00.000,...,2061,133,130,CENTRAL,2490893.402,6971091.929,null,None,None,2019
13,1984,75287,UF2019-1230,"60932, 60933, 60934",2019-09-28T00:00:00.000,5:35 PM,11368,Male,White,2017-07-26T00:00:00.000,...,6059,613,610,NORTH CENTRAL,2475207.802,7046629.116,"{""type"": ""Point"", ""coordinates"": [-96.846143, ...",14,3,2019
14,2697,75216,UF2019-1633,61954,2019-11-16T00:00:00.000,12:55 AM,11509,Male,White,2018-05-02T00:00:00.000,...,4322,727,720,SOUTH CENTRAL,2489283.104,6937390.895,"{""type"": ""Point"", ""coordinates"": [-96.806984, ...",4,3,2019
15,207,75252,UF2019-0124,55013,2019-01-28T00:00:00.000,12:30 PM,7061,Male,White,1994-07-05T00:00:00.000,...,4422,621,620,NORTH CENTRAL,2491016.32,7053489.902,"{""type"": ""Point"", ""coordinates"": [-96.795404, ...",14,3,2019
16,1061,75212,UF2019-0686,55214,2019-02-09T00:00:00.000,10:35 PM,11425,Female,White,2017-11-29T00:00:00.000,...,4038,423,420,SOUTHWEST,2474994.422,6971621.374,"{""type"": ""Point"", ""coordinates"": [-96.852421, ...",6,3,2019
17,800,75236,UF2019-0521,57246,2019-05-05T00:00:00.000,5:00 PM,9572,Male,White,2008-08-20T00:00:00.000,...,4401,435,430,SOUTHWEST,2447982.265,6930266.477,null,None,None,2019
18,2367,75202,UF2019-1427,60139,2019-08-29T00:00:00.000,8:40 PM,9881,Male,White,2009-06-10T00:00:00.000,...,2071,133,130,CENTRAL,2489689.079,6970448.413,"{""type"": ""Point"", ""coordinates"": [-96.803969, ...",12,3,2019
19,975,75228,UF2019-0627,57695,2019-05-20T00:00:00.000,11:20 PM,9675,Male,White,2008-12-10T00:00:00.000,...,1132,228,220,NORTHEAST,2536678.324,6999039.025,"{""type"": ""Point"", ""coordinates"": [-96.649175, ...",13,3,2019
20,1025,75208,UF2019-0660,58573,2019-03-31T00:00:00.000,9:20 PM,11241,Female,White,2016-11-30T00:00:00.000,...,4141,446,440,SOUTHWEST,2483587.416,6954879.596,"{""type"": ""Point"", ""coordinates"": [-96.825104, ...",1,3,2019
21,1786,75216,UF2019-1106,60054,2019-08-24T00:00:00.000,4:50 PM,11028,Male,White,2015-06-03T00:00:00.000,...,4300,726,720,SOUTH CENTRAL,2497847.071,6943020.952,"{""type"": ""Point"", ""coordinates"": [-96.778775, ...",4,3,2019
22,337,75243,UF2019-0218,"55315, 55316",2019-02-16T00:00:00.000,4:50 PM,11306,Male,White,2017-04-05T00:00:00.000,...,None,None,None,None,2520679.891,7019315.305,"{""type"": ""Point"", ""coordinates"": [-96.700482, ...",None,None,2019
23,1771,75231,UF2019-1097,59482,2019-07-31T00:00:00.000,10:30 AM,8425,Male,White,2003-08-15T00:00:00.000,...,6014,213,210,NORTHEAST,2507860.636,7002746.437,"{""type"": ""Point"", ""coordinates"": [-96.743621, ...",11,3,2019
24,409,75218,UF2019-0263,55780,2019-03-08T00:00:00.000,2:15 AM,9573,Male,Hispanic,2008-08-20T00:00:00.000,...,1100,233,230,NORTHEAST,2526618.478,6998483.295,"{""type"": ""Point"", ""coordinates"": [-96.681572, ...",13,3,2019
25,1612,75218,UF2019-1000,"60461, 60462",2019-04-10T00:00:00.000,4:48 AM,11473,Female,White,2018-02-21T00:00:00.000,...,1114,232,230,NORTHEAST,2525944.808,6996333.292,"{""type"": ""Point"", ""coordinates"": [-96.684775, ...",13,3,2019
26,296,75216,UF2019-0192,54821,2019-01-25T00:00:00.000,9:50 AM,10021,Male,White,2009-11-11T00:00:00.000,...,4225,728,720,SOUTH CENTRAL,2497160.963,6947606.047,"{""type"": ""Point"", ""coordinates"": [-96.780455, ...",4,3,2019
27,42,75241,UF2019-0026,54270,2019-01-01T00:00:00.000,7:10 PM,11281,Male,Other,2017-02-22T00:00:00.000,...,4326,735,730,SOUTH CENTRAL,2498243.117,6937364.104,"{""type"": ""Point"", ""coordinates"": [-96.777632, ...",8,3,2019
28,1243,75210,UF2019-0785,"57169, 57170",2019-05-02T00:00:00.000,6:15 PM,10695,Male,White,2013-11-06T00:00:00.000,...,2150,313,310,SOUTHEAST,2509968.529,6965321.722,"{""type"": ""Point"", ""coordinates"": [-96.738253, ...",7,3,2019
29,1556,75212,UF2019-0968,59189,2019-07-18T00:00:00.000,8:15 PM,11039,Male,White,2015-06-17T00:00:00.000,...,4012,422,420,SOUTHWEST,2472250.476,6973242.286,"{""type"": ""Point"", ""coordinates"": [-96.860527, ...",6,3,2019

In [23]:
# load into table
df_2019[table_cols].to_sql('uof_filenum',engine,schema='cdep',if_exists='append',index=False,method='multi')

## Load 2018 data

In [ ]:
## Should fix the trailing zeros in the current_ba

In [8]:
df_2018 = pd.DataFrame(client.get(url_dict['data_2018'], limit=limit))

In [9]:
df_2018.columns

Index(['filenum', 'uofnum', 'occurred_d', 'current_ba', 'offsex', 'offrace',
       'hire_dt', 'off_injure', 'offcondtyp', 'off_hospit', 'service_ty',
       'forcetype', 'uof_reason', 'cycles_num', 'forceeffec', 'street_n',
       'street', 'street_g', 'street_t', 'address', 'citnum', 'citrace',
       'citsex', 'cit_injure', 'citcondtyp', 'cit_arrest', 'cit_infl_a',
       'citcharget', 'ra', 'beat', 'sector', 'division', 'geocoded_column',
       ':@computed_region_sjyw_rtbm', ':@computed_region_2f7u_b5gs'],
      dtype='object')

In [12]:
df_2018.groupby('current_ba')['filenum'].count()

current_ba
0E-11                6
10005.00000000000    3
10009.00000000000    2
10013.00000000000    1
10020.00000000000    1
                    ..
9975.00000000000     1
9990.00000000000     2
9993.00000000000     1
9994.00000000000     2
9996.00000000000     2
Name: filenum, Length: 1047, dtype: int64

In [24]:
df_2018['current_ba'].sort_values().head(10)

2019                0E-11
2465                0E-11
2699                0E-11
2427                0E-11
1965                0E-11
1099                0E-11
2235    10005.00000000000
785     10005.00000000000
898     10005.00000000000
1598    10009.00000000000
Name: current_ba, dtype: object

In [29]:
df_2018.iloc[1099]

filenum                                                              UF2018-1239
uofnum                                                                     52493
occurred_d                                               2018-09-30T00:00:00.000
current_ba                                                                 0E-11
offsex                                                                    Female
offrace                                                                    Asian
hire_dt                                                  2017-06-28T00:00:00.000
off_injure                                                                    No
offcondtyp                                          No injuries noted or visible
off_hospit                                                                    No
service_ty                                                                Arrest
forcetype                                               Weapon display at Person
uof_reason                                                                 Other
cycles_num                                                                  NULL
forceeffec                                                                   Yes
street_n                                                        2620.00000000000
street                                                                  Highland
street_g                                                                    NULL
street_t                                                                     Rd.
address                                                        2620 Highland Rd.
citnum                                                         30436.00000000000
citrace                                                                     NULL
citsex                                                                      Male
cit_injure                                                                    No
citcondtyp                                          No injuries noted or visible
cit_arrest                                                                   Yes
cit_infl_a                                                               Unknown
citcharget                                                                 APOWW
ra                                                                          1201
beat                                                                         238
sector                                                                       230
division                                                               NORTHEAST
geocoded_column                {'type': 'Point', 'coordinates': [-74.962187, ...
:@computed_region_sjyw_rtbm                                                  NaN
:@computed_region_2f7u_b5gs                                                  NaN
Name: 1099, dtype: object

In [26]:
df_2018.head(30)

,filenum,uofnum,occurred_d,current_ba,offsex,offrace,hire_dt,off_injure,offcondtyp,off_hospit,...,cit_arrest,cit_infl_a,citcharget,ra,beat,sector,division,geocoded_column,:@computed_region_sjyw_rtbm,:@computed_region_2f7u_b5gs
0,UF2018-0945,51374,2018-08-03T00:00:00.000,8681.00000000000,Male,White,2005-08-05T00:00:00.000,No,No injuries noted or visible,No,...,Yes,Alchohol,Public Intoxication,2062,134,130,CENTRAL,"{'type': 'Point', 'coordinates': [-96.799965, ...",12,3
1,UF2018-0868,51056,2018-07-20T00:00:00.000,8019.00000000000,Male,Hispanic,2001-04-13T00:00:00.000,No,No injuries noted or visible,No,...,Yes,Mentally unstable,APOWW,4119,413,410,SOUTHWEST,"{'type': 'Point', 'coordinates': [-90.516982, ...",NaN,NaN
2,UF2018-1228,52701,2018-10-10T00:00:00.000,11171.00000000000,Male,Hispanic,2016-04-06T00:00:00.000,Yes,Laceration/Cut,No,...,Yes,Agitated,Assault/Public Servant,2073,134,130,CENTRAL,NaN,NaN,NaN
3,UF2018-0912,51050,2018-07-19T00:00:00.000,6412.00000000000,Male,Black,1990-07-16T00:00:00.000,Yes,Sprain/Strain,No,...,Yes,Alchohol,Assault,3070,523,520,NORTHWEST,NaN,NaN,NaN
4,UF2018-1014,"51858, 51859",2018-08-18T00:00:00.000,10991.00000000000,Male,White,2015-03-25T00:00:00.000,Yes,Redness/Swelling,No,...,Yes,Mentally unstable,Assault/Public Servant,1247,327,320,SOUTHEAST,"{'type': 'Point', 'coordinates': [-96.648101, ...",7,3
5,UF2018-1650,53440,2018-11-25T00:00:00.000,11459.00000000000,Male,Hispanic,2018-02-07T00:00:00.000,No,No injuries noted or visible,No,...,Yes,Agitated,"Assault/FV, Resisting Arrest",3046,526,520,NORTHWEST,"{'type': 'Point', 'coordinates': [-96.857673, ...",2,3
6,UF2018-1146,51950,2018-09-04T00:00:00.000,8940.00000000000,Male,White,2006-09-27T00:00:00.000,No,No injuries noted or visible,No,...,No,NULL,No Arrest,NaN,NaN,NaN,NaN,"{'type': 'Point', 'coordinates': [-81.582777, ...",NaN,NaN
7,UF2018-0266,48871,2018-04-02T00:00:00.000,9513.00000000000,Male,White,2008-07-09T00:00:00.000,No,No injuries noted or visible,No,...,Yes,Alchohol,"Assault/FV, Warrant/Hold",4421,625,620,NORTH CENTRAL,"{'type': 'Point', 'coordinates': [-89.11496700...",NaN,NaN
8,UF2018-0310,48859,2018-03-29T00:00:00.000,7080.00000000000,Male,White,1994-07-13T00:00:00.000,Yes,Abrasion/Scrape,No,...,Yes,None detected,Crim Trespass/Bldg/Prop,9608,258,250,NORTHEAST,NaN,NaN,NaN
9,UF2018-1427,53617,2018-12-03T00:00:00.000,9365.00000000000,Male,Asian,2008-01-23T00:00:00.000,No,No injuries noted or visible,No,...,Yes,Unknown Drugs,APOWW,3094,542,540,NORTHWEST,"{'type': 'Point', 'coordinates': [-81.209393, ...",NaN,NaN
10,UF2018-0512,"49695, 49696",2018-05-06T00:00:00.000,10652.00000000000,Male,White,2013-09-25T00:00:00.000,Yes,"Abrasion/Scrape, Fracture",Yes,...,Yes,Alchohol and unknown drugs,APOWW,2059,131,130,CENTRAL,"{'type': 'Point', 'coordinates': [-87.679265, ...",NaN,NaN
11,UF2018-0456,"49542, 49543",2018-04-30T00:00:00.000,9026.00000000000,Male,Asian,2007-01-10T00:00:00.000,No,No injuries noted or visible,No,...,Yes,Alchohol,APOWW,3004,551,550,NORTHWEST,"{'type': 'Point', 'coordinates': [-96.89586000...",6,3
12,UF2018-1600,53806,2018-12-13T00:00:00.000,11335.00000000000,Male,Black,2017-05-31T00:00:00.000,No,No injuries noted or visible,No,...,No,Agitated,No Arrest,2149,313,310,SOUTHEAST,NaN,NaN,NaN
13,UF2018-0908,49391,2018-04-24T00:00:00.000,11008.00000000000,Male,Black,2015-03-25T00:00:00.000,No,No injuries noted or visible,No,...,Yes,None detected,Warrant/Hold,NaN,NaN,NaN,NaN,"{'type': 'Point', 'coordinates': [-80.06268, 2...",NaN,NaN
14,UF2018-0403,51637,2018-01-14T00:00:00.000,10910.00000000000,Male,Black,2014-10-22T00:00:00.000,No,No injuries noted or visible,No,...,No,None detected,No Arrest,4011,422,420,SOUTHWEST,"{'type': 'Point', 'coordinates': [-96.869423, ...",6,3
15,UF2018-0135,"47511, 47514, 47516",2018-01-19T00:00:00.000,11281.00000000000,Male,Other,2017-02-22T00:00:00.000,No,No injuries noted or visible,No,...,Yes,FD-Suspect Unarmed,Assault/FV,4300,726,720,SOUTH CENTRAL,"{'type': 'Point', 'coordinates': [-96.778927, ...",4,3
16,UF2018-1168,51783,2018-08-27T00:00:00.000,7827.00000000000,Male,Black,1999-09-17T00:00:00.000,Yes,No injuries noted or visible,No,...,Yes,Agitated,Assault,4357,737,730,SOUTH CENTRAL,"{'type': 'Point', 'coordinates': [-96.762413, ...",8,3
17,UF2018-1200,52137,2018-09-14T00:00:00.000,9649.00000000000,Male,White,2008-10-29T00:00:00.000,No,No injuries noted or visible,No,...,Yes,Agitated,Crim Trespass/Bldg/Prop,4345,742,740,SOUTH CENTRAL,"{'type': 'Point', 'coordinates': [-96.868002, ...",3,3
18,UF2018-0654,"50299, 50300",2018-06-11T00:00:00.000,9881.00000000000,Male,White,2009-06-10T00:00:00.000,No,No injuries noted or visible,No,...,No,None detected,No Arrest,2040,122,120,CENTRAL,"{'type': 'Point', 'coordinates': [-96.808966, ...",2,3
19,UF2018-1225,52689,2018-10-10T00:00:00.000,9263.00000000000,Male,Black,2007-09-26T00:00:00.000,No,No injuries noted or visible,No,...,Yes,Agitated,Warrant/Hold,4325,727,720,SOUTH CENTRAL,NaN,NaN,NaN
20,UF2018-1129,51716,2018-08-23T00:00:00.000,10868.00000000000,Male,Hispanic,2014-08-13T00:00:00.000,No,No injuries noted or visible,No,...,Yes,NULL,"Burglary/Habitation, Resisting Arrest",2144,346,340,SOUTHEAST,"{'type': 'Point', 'coordinates': [-96.761973, ...",7,3
21,UF2018-1034,51583,2018-05-30T00:00:00.000,6250.00000000000,Male,Hispanic,1990-02-26T00:00:00.000,No,No injuries noted or visible,No,...,Yes,Unknown,"DWI, Resisting Arrest",2145,346,340,SOUTHEAST,NaN,NaN,NaN
22,UF2018-1645,53819,2018-12-14T00:00:00.000,10318.00000000000,Male,White,2012-03-28T00:00:00.000,No,No injuries noted or visible,No,...,Yes,Alchohol,Public Intoxication,4090,412,410,SOUTHWEST,"{'type': 'Point', 'coordinates': [-75.360998, ...",NaN,NaN
23,UF2018-0055,47394,2018-01-07T00:00:00.000,10510.00000000000,Male,Black,2013-04-10T00:00:00.000,No,No injuries noted or visible,No,...,Yes,Alchohol,DWI,3096,523,520,NORTHWEST,"{'type': 'Point', 'coordinates': [-96.818188, ...",2,3
24,UF2018-1073,51604,2018-08-18T00:00:00.000,8517.00000000000,Female,White,2004-06-04T00:00:00.000,No,No injuries noted or visible,No,...,Yes,Mentally unstable,APOWW,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,UF2018-1509,53458,2018-11-28T00:00:00.000,7699.00000000000,Male,Asian,1998-09-18T00:00:00.000,No,No injuries noted or visible,No,...,Yes,Alchohol,Public Intoxication,3070,523,520,NORTHWEST,"{'type': 'Point', 'coordinates': [-96.846249, ...",2,3
26,UF2018-1336,53091,2018-11-09T00:00:00.000,10333.00000000000,Male,Hispanic,2012-03-28T00:00:00.000,No,No injuries noted or visible,No,...,Yes,Unknown,"Evading Arrest, Unauthorize Use Vehicle",1249,332,330,SOUTHEAST,"{'type': 'Point', 'coordinates': [-96.692989, ...",5,3
27,UF2018-0860,49942,2018-05-23T00:00:00.000,6683.00000000000,Male,White,1991-07-29T00:00:00.000,No,No injuries noted or visible,No,...,Yes,Unknown,"Evading Arrest, Warrant/Hold",2084,115,110,CENTRAL,"{'type': 'Point', 'coordinates': [-96.757644, ...",2,3
28,UF2018-0567,49870,2018-05-20T00:00:00.000,9565.00000000000,Male,White,2008-08-20T00:00:00.000,No,No injuries noted or visible,No,...,Yes,Mentally unstable,APOWW,2201,336,330,SOUTHEAST,"{'type': 'Point', 'coordinates': [-96.687754, ...",5,3
29,UF2018-0787,50699,2018-07-02T00:00:00.000,11307.00000000000,Male,White,2017-04-05T00:00:00.000,No,No injuries noted or visible,No,...,Yes,Unknown Drugs,Public Intoxication,3116,546,540,NORTHWEST,NaN,NaN,NaN

In [27]:
# replace NaN string values with None type for proper load into database
df_2018.replace(to_replace='NaN',inplace=True)

filenum                        None
uofnum                         None
occurred_d                     None
current_ba                     None
offsex                         None
offrace                        None
hire_dt                        None
off_injure                     None
offcondtyp                     None
off_hospit                     None
service_ty                     None
forcetype                      None
uof_reason                     None
cycles_num                     None
forceeffec                     None
street_n                       None
street                         None
street_g                       None
street_t                       None
address                        None
citnum                         None
citrace                        None
citsex                         None
cit_injure                     None
citcondtyp                     None
cit_arrest                     None
cit_infl_a                     None
citcharget                     None
ra                             None
beat                           None
sector                         None
division                       None
geocoded_column                None
:@computed_region_sjyw_rtbm    None
:@computed_region_2f7u_b5gs    None
dtype: object

In [28]:
# cast all empty values into None type
df_2018.where(pd.notnull(df_2018),None,inplace=True)

In [29]:
# convert the geocode column from dict to JSON string for load into database
df_2018['geocoded_column'] = df_2018['geocoded_column'].apply(lambda x:json.dumps(x))

In [30]:
# replace NULL string values with None type for proper load into database
df_2018.replace(to_replace='NULL',inplace=True)

filenum                        None
uofnum                         None
occurred_d                     None
current_ba                     None
offsex                         None
offrace                        None
hire_dt                        None
off_injure                     None
offcondtyp                     None
off_hospit                     None
service_ty                     None
forcetype                      None
uof_reason                     None
cycles_num                     None
forceeffec                     None
street_n                       None
street                         None
street_g                       None
street_t                       None
address                        None
citnum                         None
citrace                        None
citsex                         None
cit_injure                     None
citcondtyp                     None
cit_arrest                     None
cit_infl_a                     None
citcharget                     None
ra                             None
beat                           None
sector                         None
division                       None
geocoded_column                None
:@computed_region_sjyw_rtbm    None
:@computed_region_2f7u_b5gs    None
dtype: object

In [31]:
# adding the year reported values
df_2018['year_reported'] = '2018'

In [32]:
df_2018.head(30)

,filenum,uofnum,occurred_d,current_ba,offsex,offrace,hire_dt,off_injure,offcondtyp,off_hospit,...,cit_infl_a,citcharget,ra,beat,sector,division,geocoded_column,:@computed_region_sjyw_rtbm,:@computed_region_2f7u_b5gs,year_reported
0,UF2018-0945,51374,2018-08-03T00:00:00.000,8681.00000000000,Male,White,2005-08-05T00:00:00.000,No,No injuries noted or visible,No,...,Alchohol,Public Intoxication,2062,134,130,CENTRAL,"{""type"": ""Point"", ""coordinates"": [-96.799965, ...",12,3,2018
1,UF2018-0868,51056,2018-07-20T00:00:00.000,8019.00000000000,Male,Hispanic,2001-04-13T00:00:00.000,No,No injuries noted or visible,No,...,Mentally unstable,APOWW,4119,413,410,SOUTHWEST,"{""type"": ""Point"", ""coordinates"": [-90.516982, ...",None,None,2018
2,UF2018-1228,52701,2018-10-10T00:00:00.000,11171.00000000000,Male,Hispanic,2016-04-06T00:00:00.000,Yes,Laceration/Cut,No,...,Agitated,Assault/Public Servant,2073,134,130,CENTRAL,null,None,None,2018
3,UF2018-0912,51050,2018-07-19T00:00:00.000,6412.00000000000,Male,Black,1990-07-16T00:00:00.000,Yes,Sprain/Strain,No,...,Alchohol,Assault,3070,523,520,NORTHWEST,null,None,None,2018
4,UF2018-1014,"51858, 51859",2018-08-18T00:00:00.000,10991.00000000000,Male,White,2015-03-25T00:00:00.000,Yes,Redness/Swelling,No,...,Mentally unstable,Assault/Public Servant,1247,327,320,SOUTHEAST,"{""type"": ""Point"", ""coordinates"": [-96.648101, ...",7,3,2018
5,UF2018-1650,53440,2018-11-25T00:00:00.000,11459.00000000000,Male,Hispanic,2018-02-07T00:00:00.000,No,No injuries noted or visible,No,...,Agitated,"Assault/FV, Resisting Arrest",3046,526,520,NORTHWEST,"{""type"": ""Point"", ""coordinates"": [-96.857673, ...",2,3,2018
6,UF2018-1146,51950,2018-09-04T00:00:00.000,8940.00000000000,Male,White,2006-09-27T00:00:00.000,No,No injuries noted or visible,No,...,Agitated,No Arrest,None,None,None,None,"{""type"": ""Point"", ""coordinates"": [-81.582777, ...",None,None,2018
7,UF2018-0266,48871,2018-04-02T00:00:00.000,9513.00000000000,Male,White,2008-07-09T00:00:00.000,No,No injuries noted or visible,No,...,Alchohol,"Assault/FV, Warrant/Hold",4421,625,620,NORTH CENTRAL,"{""type"": ""Point"", ""coordinates"": [-89.11496700...",None,None,2018
8,UF2018-0310,48859,2018-03-29T00:00:00.000,7080.00000000000,Male,White,1994-07-13T00:00:00.000,Yes,Abrasion/Scrape,No,...,None detected,Crim Trespass/Bldg/Prop,9608,258,250,NORTHEAST,null,None,None,2018
9,UF2018-1427,53617,2018-12-03T00:00:00.000,9365.00000000000,Male,Asian,2008-01-23T00:00:00.000,No,No injuries noted or visible,No,...,Unknown Drugs,APOWW,3094,542,540,NORTHWEST,"{""type"": ""Point"", ""coordinates"": [-81.209393, ...",None,None,2018
10,UF2018-0512,"49695, 49696",2018-05-06T00:00:00.000,10652.00000000000,Male,White,2013-09-25T00:00:00.000,Yes,"Abrasion/Scrape, Fracture",Yes,...,Alchohol and unknown drugs,APOWW,2059,131,130,CENTRAL,"{""type"": ""Point"", ""coordinates"": [-87.679265, ...",None,None,2018
11,UF2018-0456,"49542, 49543",2018-04-30T00:00:00.000,9026.00000000000,Male,Asian,2007-01-10T00:00:00.000,No,No injuries noted or visible,No,...,Alchohol,APOWW,3004,551,550,NORTHWEST,"{""type"": ""Point"", ""coordinates"": [-96.89586000...",6,3,2018
12,UF2018-1600,53806,2018-12-13T00:00:00.000,11335.00000000000,Male,Black,2017-05-31T00:00:00.000,No,No injuries noted or visible,No,...,Agitated,No Arrest,2149,313,310,SOUTHEAST,null,None,None,2018
13,UF2018-0908,49391,2018-04-24T00:00:00.000,11008.00000000000,Male,Black,2015-03-25T00:00:00.000,No,No injuries noted or visible,No,...,None detected,Warrant/Hold,None,None,None,None,"{""type"": ""Point"", ""coordinates"": [-80.06268, 2...",None,None,2018
14,UF2018-0403,51637,2018-01-14T00:00:00.000,10910.00000000000,Male,Black,2014-10-22T00:00:00.000,No,No injuries noted or visible,No,...,None detected,No Arrest,4011,422,420,SOUTHWEST,"{""type"": ""Point"", ""coordinates"": [-96.869423, ...",6,3,2018
15,UF2018-0135,"47511, 47514, 47516",2018-01-19T00:00:00.000,11281.00000000000,Male,Other,2017-02-22T00:00:00.000,No,No injuries noted or visible,No,...,FD-Suspect Unarmed,Assault/FV,4300,726,720,SOUTH CENTRAL,"{""type"": ""Point"", ""coordinates"": [-96.778927, ...",4,3,2018
16,UF2018-1168,51783,2018-08-27T00:00:00.000,7827.00000000000,Male,Black,1999-09-17T00:00:00.000,Yes,No injuries noted or visible,No,...,Agitated,Assault,4357,737,730,SOUTH CENTRAL,"{""type"": ""Point"", ""coordinates"": [-96.762413, ...",8,3,2018
17,UF2018-1200,52137,2018-09-14T00:00:00.000,9649.00000000000,Male,White,2008-10-29T00:00:00.000,No,No injuries noted or visible,No,...,Agitated,Crim Trespass/Bldg/Prop,4345,742,740,SOUTH CENTRAL,"{""type"": ""Point"", ""coordinates"": [-96.868002, ...",3,3,2018
18,UF2018-0654,"50299, 50300",2018-06-11T00:00:00.000,9881.00000000000,Male,White,2009-06-10T00:00:00.000,No,No injuries noted or visible,No,...,None detected,No Arrest,2040,122,120,CENTRAL,"{""type"": ""Point"", ""coordinates"": [-96.808966, ...",2,3,2018
19,UF2018-1225,52689,2018-10-10T00:00:00.000,9263.00000000000,Male,Black,2007-09-26T00:00:00.000,No,No injuries noted or visible,No,...,Agitated,Warrant/Hold,4325,727,720,SOUTH CENTRAL,null,None,None,2018
20,UF2018-1129,51716,2018-08-23T00:00:00.000,10868.00000000000,Male,Hispanic,2014-08-13T00:00:00.000,No,No injuries noted or visible,No,...,Agitated,"Burglary/Habitation, Resisting Arrest",2144,346,340,SOUTHEAST,"{""type"": ""Point"", ""coordinates"": [-96.761973, ...",7,3,2018
21,UF2018-1034,51583,2018-05-30T00:00:00.000,6250.00000000000,Male,Hispanic,1990-02-26T00:00:00.000,No,No injuries noted or visible,No,...,Unknown,"DWI, Resisting Arrest",2145,346,340,SOUTHEAST,null,None,None,2018
22,UF2018-1645,53819,2018-12-14T00:00:00.000,10318.00000000000,Male,White,2012-03-28T00:00:00.000,No,No injuries noted or visible,No,...,Alchohol,Public Intoxication,4090,412,410,SOUTHWEST,"{""type"": ""Point"", ""coordinates"": [-75.360998, ...",None,None,2018
23,UF2018-0055,47394,2018-01-07T00:00:00.000,10510.00000000000,Male,Black,2013-04-10T00:00:00.000,No,No injuries noted or visible,No,...,Alchohol,DWI,3096,523,520,NORTHWEST,"{""type"": ""Point"", ""coordinates"": [-96.818188, ...",2,3,2018
24,UF2018-1073,51604,2018-08-18T00:00:00.000,8517.00000000000,Female,White,2004-06-04T00:00:00.000,No,No injuries noted or visible,No,...,Mentally unstable,APOWW,None,None,None,None,null,None,None,2018
25,UF2018-1509,53458,2018-11-28T00:00:00.000,7699.00000000000,Male,Asian,1998-09-18T00:00:00.000,No,No injuries noted or visible,No,...,Alchohol,Public Intoxication,3070,523,520,NORTHWEST,"{""type"": ""Point"", ""coordinates"": [-96.846249, ...",2,3,2018
26,UF2018-1336,53091,2018-11-09T00:00:00.000,10333.00000000000,Male,Hispanic,2012-03-28T00:00:00.000,No,No injuries noted or visible,No,...,Unknown,"Evading Arrest, Unauthorize Use Vehicle",1249,332,330,SOUTHEAST,"{""type"": ""Point"", ""coordinates"": [-96.692989, ...",5,3,2018
27,UF2018-0860,49942,2018-05-23T00:00:00.000,6683.00000000000,Male,White,1991-07-29T00:00:00.000,No,No injuries noted or visible,No,...,Unknown,"Evading Arrest, Warrant/Hold",2084,115,110,CENTRAL,"{""type"": ""Point"", ""coordinates"": [-96.757644, ...",2,3,2018
28,UF2018-0567,49870,2018-05-20T00:00:00.000,9565.00000000000,Male,White,2008-08-20T00:00:00.000,No,No injuries noted or visible,No,...,Mentally unstable,APOWW,2201,336,330,SOUTHEAST,"{""type"": ""Point"", ""coordinates"": [-96.687754, ...",5,3,2018
29,UF2018-0787,50699,2018-07-02T00:00:00.000,11307.00000000000,Male,White,2017-04-05T00:00:00.000,No,No injuries noted or visible,No,...,Unknown Drugs,Public Intoxication,3116,546,540,NORTHWEST,null,None,None,2018

In [33]:
# load into table
df_2018[[item for item in table_cols if item in df_2018.columns]].to_sql('uof_filenum',engine,schema='cdep',if_exists='append',index=True,index_label='objectid',method='multi')

- - -

## Load 2017 Data

In [34]:
df_2017 = pd.DataFrame(client.get(url_dict['data_2017'], limit=limit))

In [35]:
df_2017.head(20)

,objectid_1,filenum,uofnum,address,occurred_d,occurred_t,current_ba,offsex,offrace,hire_dt,...,beat,sector,division,dist_name,x,y,geolocation,:@computed_region_sjyw_rtbm,:@computed_region_2f7u_b5gs,taag_name
0,1063,UF2017-1685,45836,220 W CAMP WISDOM RD,2017-10-24T00:00:00.000,10:30 AM,11217,Female,Hispanic,2016-09-07T00:00:00.000,...,747,740,SOUTH CENTRAL,D8,2483989.795963,6927942.126927,"{'type': 'Point', 'coordinates': [-96.824112, ...",8,3,NaN
1,1367,UF2017-1878,47141,1531 POCONO TRL,2017-12-25T00:00:00.000,5:30 PM,11285,Male,White,2017-03-08T00:00:00.000,...,327,320,SOUTHEAST,D5,2539821.664527,6956486.797079,"{'type': 'Point', 'coordinates': [-96.641689, ...",5,3,NaN
2,1438,UF2017-1927,46916,8145 HUNNICUT RD,2017-11-28T00:00:00.000,1:12 AM,10224,Male,White,2010-08-18T00:00:00.000,...,237,230,NORTHEAST,D7,2519568.339560,6978413.242452,"{'type': 'Point', 'coordinates': [-96.706316, ...",7,3,NaN
3,2198,UF2017-662,41532,7814 N CENTRAL EXPY,2017-04-18T00:00:00.000,11:41 AM,5260,Male,White,1985-08-15T00:00:00.000,...,214,210,NORTHEAST,D14,2499646.679584,6999604.605725,"{'type': 'Point', 'coordinates': [-96.769859, ...",12,3,Central Southwestern*
4,2573,UF2017-912,43186,3000 MUNICIPAL ST,2017-06-18T00:00:00.000,5:58 PM,9388,Male,White,2008-02-20T00:00:00.000,...,351,350,SOUTHEAST,D7,2508016.266634,6956733.492611,"{'type': 'Point', 'coordinates': [-96.745228, ...",7,3,NaN
5,2036,UF2017-561,"40432, 40433, 41431",1720 WOOD ST,2017-03-09T00:00:00.000,9:18 AM,8321,Male,Black,2002-09-13T00:00:00.000,...,134,130,CENTRAL,D2,2492217.494981,6970630.126899,"{'type': 'Point', 'coordinates': [-96.795932, ...",12,3,NaN
6,2651,UF2017-965,"42928, 42929",160 E AIRPORT FWY,2017-03-19T00:00:00.000,3:00 AM,9709,Male,Hispanic,2009-01-07T00:00:00.000,...,0,0,NaN,NaN,0.000000,0.000000,NaN,NaN,NaN,NaN
7,1162,UF2017-1741,46173,2911 E LEDBETTER DR,2017-11-05T00:00:00.000,5:03 PM,10998,Male,White,2015-03-25T00:00:00.000,...,733,730,SOUTH CENTRAL,D4,2500054.985552,6940069.640364,"{'type': 'Point', 'coordinates': [-96.771562, ...",4,3,Great Trinity Forest BonnieView*
8,2336,UF2017-764,"41695, 42056",4600 S MALCOLM X BLVD,2017-04-25T00:00:00.000,2:50 AM,7896,Male,White,2000-05-10T00:00:00.000,...,346,340,SOUTHEAST,D7,2505343.370728,6962661.133308,NaN,NaN,NaN,Hatcher Scyene*
9,183,UF2017-1100,"43581, 43582",9727 WHITEHURST DR,2017-07-07T00:00:00.000,12:34 AM,9134,Male,White,2007-05-30T00:00:00.000,...,242,240,NORTHEAST,D10,2512709.712169,7015414.940771,"{'type': 'Point', 'coordinates': [-96.727081, ...",9,3,NaN
10,2559,UF2017-904,"43068, 43069",13550 DALLAS PKWY,2017-06-13T00:00:00.000,12:15 PM,6154,Male,White,1989-11-02T00:00:00.000,...,633,630,NORTH CENTRAL,D11,2483395.359319,7026295.764010,"{'type': 'Point', 'coordinates': [-96.821618, ...",10,3,SpringValley Preston*
11,761,UF2017-1493,44719,3903 MICAN DR,2017-08-21T00:00:00.000,11:13 PM,9571,Male,White,2008-08-20T00:00:00.000,...,421,420,SOUTHWEST,D6,2462919.204835,6973862.455218,"{'type': 'Point', 'coordinates': [-96.890909, ...",6,3,NaN
12,405,UF2017-1240,44485,3653 TIMBERGLEN RD,2017-08-21T00:00:00.000,5:07 PM,10641,Male,White,2013-09-25T00:00:00.000,...,612,610,NORTH CENTRAL,D12,2473677.749619,7050727.770889,"{'type': 'Point', 'coordinates': [-96.852619, ...",14,3,NaN
13,1805,UF2017-357,"39813, 39814",4619 SPRING GARDEN AVE,2017-02-14T00:00:00.000,11:20 PM,10847,Male,Hispanic,2014-06-18T00:00:00.000,...,346,340,SOUTHEAST,D7,2507027.766744,6964528.905164,"{'type': 'Point', 'coordinates': [-96.747638, ...",7,3,Hatcher Scyene*
14,421,UF2017-1248,44764,15830 PRESTON RD,2017-08-29T00:00:00.000,7:30 PM,8014,Male,White,2001-04-13T00:00:00.000,...,622,620,NORTH CENTRAL,D12,2488526.405474,7037460.336856,"{'type': 'Point', 'coordinates': [-96.804389, ...",14,3,NaN
15,1259,UF2017-1802,48010,1200 TORONTO ST,2017-12-16T00:00:00.000,6:40 AM,11145,Male,White,2016-02-24T00:00:00.000,...,423,420,SOUTHWEST,D6,2478364.241390,6970534.692652,"{'type': 'Point', 'coordinates': [-96.841124, ...",6,3,NaN
16,2431,UF2017-822,42497,15678 KNOLL TRAIL DR,2017-05-12T00:00:00.000,1:20 AM,7310,Male,White,1995-11-08T00:00:00.000,...,622,620,NORTH CENTRAL,D11,2484046.541380,7038725.963311,"{'type': 'Point', 'coordinates': [-96.818923, ...",10,3,NaN
17,2454,UF2017-843,"39762, 39763",423 E LEDBETTER DR,2017-02-11T00:00:00.000,7:20 PM,8312,Female,White,2002-09-13T00:00:00.000,...,751,750,SOUTH CENTRAL,D4,2485856.510152,6936215.460278,"{'type': 'Point', 'coordinates': [-96.819274, ...",4,3,NaN
18,2062,UF2017-577,40850,18900 DALLAS PKWY,2017-03-24T00:00:00.000,7:50 PM,9705,Male,White,2009-01-07T00:00:00.000,...,614,610,NORTH CENTRAL,D12,2480767.215213,7053027.541224,"{'type': 'Point', 'coordinates': [-96.8289, 33...",14,3,NaN
19,2646,UF2017-963,41805,1019 S EDGEFIELD AVE,2017-04-28T00:00:00.000,9:50 PM,10937,Male,White,2014-12-03T00:00:00.000,...,444,440,SOUTHWEST,D1,2477561.573597,6954720.330250,"{'type': 'Point', 'coordinates': [-96.844278, ...",1,3,NaN

In [36]:
df_2017.columns

Index(['objectid_1', 'filenum', 'uofnum', 'address', 'occurred_d',
       'occurred_t', 'current_ba', 'offsex', 'offrace', 'hire_dt',
       'off_injure', 'offcondtyp', 'off_hospit', 'service_ty', 'forcetype',
       'uof_reason', 'cycles_num', 'forceeffec', 'street_n', 'street',
       'street_g', 'street_t', 'citnum', 'citrace', 'citsex', 'cit_injure',
       'citcondtyp', 'cit_arrest', 'cit_infl_a', 'citcharget', 'ra', 'beat',
       'sector', 'division', 'dist_name', 'x', 'y', 'geolocation',
       ':@computed_region_sjyw_rtbm', ':@computed_region_2f7u_b5gs',
       'taag_name'],
      dtype='object')

In [37]:
# rename columns
df_2017.rename(columns={'objectid_1':'objectid', 'dist_name':'council_district','geolocation':'geocoded_column'},inplace=True)

In [38]:
# fix issue with the boolean types 
df_2017 = df_2017.astype({'off_injure':'str', 'off_hospit':'str', 'cit_injure':'str', 'cit_arrest':'str'})

In [39]:
# replace NaN string values with None type for proper load into database
df_2017.replace(to_replace='NaN',value=None,inplace=True)

objectid                       None
filenum                        None
uofnum                         None
address                        None
occurred_d                     None
occurred_t                     None
current_ba                     None
offsex                         None
offrace                        None
hire_dt                        None
off_injure                     None
offcondtyp                     None
off_hospit                     None
service_ty                     None
forcetype                      None
uof_reason                     None
cycles_num                     None
forceeffec                     None
street_n                       None
street                         None
street_g                       None
street_t                       None
citnum                         None
citrace                        None
citsex                         None
cit_injure                     None
citcondtyp                     None
cit_arrest                     None
cit_infl_a                     None
citcharget                     None
ra                             None
beat                           None
sector                         None
division                       None
council_district               None
x                              None
y                              None
geocoded_column                None
:@computed_region_sjyw_rtbm    None
:@computed_region_2f7u_b5gs    None
taag_name                      None
dtype: object

In [40]:
# cast all empty values into None type
df_2017.where(df_2017.notnull(),other=None,inplace=True)

In [41]:
# convert the geocode column from dict to JSON string for load into database
df_2017['geocoded_column'] = df_2017['geocoded_column'].apply(lambda x:json.dumps(x))

In [42]:
# replace NULL string values with None type for proper load into database
df_2017.replace(to_replace='NULL',inplace=True)

objectid                       None
filenum                        None
uofnum                         None
address                        None
occurred_d                     None
occurred_t                     None
current_ba                     None
offsex                         None
offrace                        None
hire_dt                        None
off_injure                     None
offcondtyp                     None
off_hospit                     None
service_ty                     None
forcetype                      None
uof_reason                     None
cycles_num                     None
forceeffec                     None
street_n                       None
street                         None
street_g                       None
street_t                       None
citnum                         None
citrace                        None
citsex                         None
cit_injure                     None
citcondtyp                     None
cit_arrest                     None
cit_infl_a                     None
citcharget                     None
ra                             None
beat                           None
sector                         None
division                       None
council_district               None
x                              None
y                              None
geocoded_column                None
:@computed_region_sjyw_rtbm    None
:@computed_region_2f7u_b5gs    None
taag_name                      None
dtype: object

In [43]:
# adding the year reported values
df_2017['year_reported'] = '2017'

In [44]:
df_2017.head(20)

,objectid,filenum,uofnum,address,occurred_d,occurred_t,current_ba,offsex,offrace,hire_dt,...,sector,division,council_district,x,y,geocoded_column,:@computed_region_sjyw_rtbm,:@computed_region_2f7u_b5gs,taag_name,year_reported
0,1063,UF2017-1685,45836,220 W CAMP WISDOM RD,2017-10-24T00:00:00.000,10:30 AM,11217,Female,Hispanic,2016-09-07T00:00:00.000,...,740,SOUTH CENTRAL,D8,2483989.795963,6927942.126927,"{""type"": ""Point"", ""coordinates"": [-96.824112, ...",8,3,None,2017
1,1367,UF2017-1878,47141,1531 POCONO TRL,2017-12-25T00:00:00.000,5:30 PM,11285,Male,White,2017-03-08T00:00:00.000,...,320,SOUTHEAST,D5,2539821.664527,6956486.797079,"{""type"": ""Point"", ""coordinates"": [-96.641689, ...",5,3,None,2017
2,1438,UF2017-1927,46916,8145 HUNNICUT RD,2017-11-28T00:00:00.000,1:12 AM,10224,Male,White,2010-08-18T00:00:00.000,...,230,NORTHEAST,D7,2519568.339560,6978413.242452,"{""type"": ""Point"", ""coordinates"": [-96.706316, ...",7,3,None,2017
3,2198,UF2017-662,41532,7814 N CENTRAL EXPY,2017-04-18T00:00:00.000,11:41 AM,5260,Male,White,1985-08-15T00:00:00.000,...,210,NORTHEAST,D14,2499646.679584,6999604.605725,"{""type"": ""Point"", ""coordinates"": [-96.769859, ...",12,3,Central Southwestern*,2017
4,2573,UF2017-912,43186,3000 MUNICIPAL ST,2017-06-18T00:00:00.000,5:58 PM,9388,Male,White,2008-02-20T00:00:00.000,...,350,SOUTHEAST,D7,2508016.266634,6956733.492611,"{""type"": ""Point"", ""coordinates"": [-96.745228, ...",7,3,None,2017
5,2036,UF2017-561,"40432, 40433, 41431",1720 WOOD ST,2017-03-09T00:00:00.000,9:18 AM,8321,Male,Black,2002-09-13T00:00:00.000,...,130,CENTRAL,D2,2492217.494981,6970630.126899,"{""type"": ""Point"", ""coordinates"": [-96.795932, ...",12,3,None,2017
6,2651,UF2017-965,"42928, 42929",160 E AIRPORT FWY,2017-03-19T00:00:00.000,3:00 AM,9709,Male,Hispanic,2009-01-07T00:00:00.000,...,0,None,None,0.000000,0.000000,null,None,None,None,2017
7,1162,UF2017-1741,46173,2911 E LEDBETTER DR,2017-11-05T00:00:00.000,5:03 PM,10998,Male,White,2015-03-25T00:00:00.000,...,730,SOUTH CENTRAL,D4,2500054.985552,6940069.640364,"{""type"": ""Point"", ""coordinates"": [-96.771562, ...",4,3,Great Trinity Forest BonnieView*,2017
8,2336,UF2017-764,"41695, 42056",4600 S MALCOLM X BLVD,2017-04-25T00:00:00.000,2:50 AM,7896,Male,White,2000-05-10T00:00:00.000,...,340,SOUTHEAST,D7,2505343.370728,6962661.133308,null,None,None,Hatcher Scyene*,2017
9,183,UF2017-1100,"43581, 43582",9727 WHITEHURST DR,2017-07-07T00:00:00.000,12:34 AM,9134,Male,White,2007-05-30T00:00:00.000,...,240,NORTHEAST,D10,2512709.712169,7015414.940771,"{""type"": ""Point"", ""coordinates"": [-96.727081, ...",9,3,None,2017
10,2559,UF2017-904,"43068, 43069",13550 DALLAS PKWY,2017-06-13T00:00:00.000,12:15 PM,6154,Male,White,1989-11-02T00:00:00.000,...,630,NORTH CENTRAL,D11,2483395.359319,7026295.764010,"{""type"": ""Point"", ""coordinates"": [-96.821618, ...",10,3,SpringValley Preston*,2017
11,761,UF2017-1493,44719,3903 MICAN DR,2017-08-21T00:00:00.000,11:13 PM,9571,Male,White,2008-08-20T00:00:00.000,...,420,SOUTHWEST,D6,2462919.204835,6973862.455218,"{""type"": ""Point"", ""coordinates"": [-96.890909, ...",6,3,None,2017
12,405,UF2017-1240,44485,3653 TIMBERGLEN RD,2017-08-21T00:00:00.000,5:07 PM,10641,Male,White,2013-09-25T00:00:00.000,...,610,NORTH CENTRAL,D12,2473677.749619,7050727.770889,"{""type"": ""Point"", ""coordinates"": [-96.852619, ...",14,3,None,2017
13,1805,UF2017-357,"39813, 39814",4619 SPRING GARDEN AVE,2017-02-14T00:00:00.000,11:20 PM,10847,Male,Hispanic,2014-06-18T00:00:00.000,...,340,SOUTHEAST,D7,2507027.766744,6964528.905164,"{""type"": ""Point"", ""coordinates"": [-96.747638, ...",7,3,Hatcher Scyene*,2017
14,421,UF2017-1248,44764,15830 PRESTON RD,2017-08-29T00:00:00.000,7:30 PM,8014,Male,White,2001-04-13T00:00:00.000,...,620,NORTH CENTRAL,D12,2488526.405474,7037460.336856,"{""type"": ""Point"", ""coordinates"": [-96.804389, ...",14,3,None,2017
15,1259,UF2017-1802,48010,1200 TORONTO ST,2017-12-16T00:00:00.000,6:40 AM,11145,Male,White,2016-02-24T00:00:00.000,...,420,SOUTHWEST,D6,2478364.241390,6970534.692652,"{""type"": ""Point"", ""coordinates"": [-96.841124, ...",6,3,None,2017
16,2431,UF2017-822,42497,15678 KNOLL TRAIL DR,2017-05-12T00:00:00.000,1:20 AM,7310,Male,White,1995-11-08T00:00:00.000,...,620,NORTH CENTRAL,D11,2484046.541380,7038725.963311,"{""type"": ""Point"", ""coordinates"": [-96.818923, ...",10,3,None,2017
17,2454,UF2017-843,"39762, 39763",423 E LEDBETTER DR,2017-02-11T00:00:00.000,7:20 PM,8312,Female,White,2002-09-13T00:00:00.000,...,750,SOUTH CENTRAL,D4,2485856.510152,6936215.460278,"{""type"": ""Point"", ""coordinates"": [-96.819274, ...",4,3,None,2017
18,2062,UF2017-577,40850,18900 DALLAS PKWY,2017-03-24T00:00:00.000,7:50 PM,9705,Male,White,2009-01-07T00:00:00.000,...,610,NORTH CENTRAL,D12,2480767.215213,7053027.541224,"{""type"": ""Point"", ""coordinates"": [-96.8289, 33...",14,3,None,2017
19,2646,UF2017-963,41805,1019 S EDGEFIELD AVE,2017-04-28T00:00:00.000,9:50 PM,10937,Male,White,2014-12-03T00:00:00.000,...,440,SOUTHWEST,D1,2477561.573597,6954720.330250,"{""type"": ""Point"", ""coordinates"": [-96.844278, ...",1,3,None,2017

In [45]:
# load into table
df_2017[[item for item in table_cols if item in df_2017.columns]].to_sql('uof_filenum',engine,schema='cdep',if_exists='append',index=False,method='multi')

## Load 2016 Data

In [46]:
df_2016 = pd.DataFrame(client.get(url_dict['data_2016'], limit=limit))

In [47]:
df_2016.columns

Index(['objectid', 'filenum', 'uofnum', 'address', 'occurred_d', 'occurred_t',
       'current_ba', 'offsex', 'offrace', 'hire_dt', 'off_injure',
       'offcondtyp', 'off_hospit', 'service_ty', 'forcetype', 'uof_reason',
       'cycles_num', 'forceeffec', 'street_n', 'street', 'street_g',
       'street_t', 'citnum', 'citrace', 'citsex', 'cit_injure', 'citcondtyp',
       'cit_arrest', 'cit_infl_a', 'citcharget', 'ra', 'beat', 'sector',
       'division', 'dist_name', 'taag_name', 'geolocation',
       ':@computed_region_sjyw_rtbm', ':@computed_region_2f7u_b5gs',
       ':@computed_region_at43_7y52', ':@computed_region_3qur_xvie',
       ':@computed_region_28rh_izyk'],
      dtype='object')

In [48]:
# rename columns
df_2016.rename(columns={'dist_name':'council_district','geolocation':'geocoded_column'},inplace=True)

In [49]:
df_2016.head(50)

,objectid,filenum,uofnum,address,occurred_d,occurred_t,current_ba,offsex,offrace,hire_dt,...,sector,division,council_district,taag_name,geocoded_column,:@computed_region_sjyw_rtbm,:@computed_region_2f7u_b5gs,:@computed_region_at43_7y52,:@computed_region_3qur_xvie,:@computed_region_28rh_izyk
0,609,UF2016-1185,37702,211 N ERVAY ST,2016-09-03T00:00:00.000,4:14:00 AM,10810,Male,Black,2014-05-07T00:00:00.000,...,130,CENTRAL,D14,,"{'latitude': '32.782205', 'longitude': '-96.79...",12,3,14,20152,3162
1,1705,UF2016-0418,33413,7647 FERGUSON RD,2016-03-22T00:00:00.000,11:00:00 PM,7706,Male,White,1999-01-08T00:00:00.000,...,230,NORTHEAST,D9,Ferguson Highland*,"{'latitude': '32.798978', 'longitude': '-96.71...",13,3,9,19361,3162
2,1239,UF2016-0616,34567,716 BIMEBELLA LN,2016-05-22T00:00:00.000,1:29:00 PM,11014,Male,Black,2015-05-20T00:00:00.000,...,430,SOUTHWEST,D6,,"{'latitude': '32.73971', 'longitude': '-96.925...",6,3,6,18528,3162
3,2320,UF2016-1349,31460,5600 L B J FWY,2016-01-10T00:00:00.000,8:55:00 PM,6692,Male,Black,1991-07-29T00:00:00.000,...,640,NORTH CENTRAL,D11,,"{'human_address': '{""address"": ""5600 L B J FWY...",NaN,NaN,NaN,NaN,NaN
4,221,UF2016-1303,"37879, 37898",4600 S MALCOLM X BLVD,2016-11-08T00:00:00.000,2:30:00 AM,9844,Male,White,2009-10-04T00:00:00.000,...,340,SOUTHEAST,D7,Hatcher Scyene*,"{'human_address': '{""address"": ""4600 S MALCOLM...",NaN,NaN,NaN,NaN,NaN
5,549,UF2016-1084,36724,1234 PEAVY RD,2016-09-11T00:00:00.000,7:20:00 PM,9855,Male,White,2009-06-10T00:00:00.000,...,230,NORTHEAST,D9,,"{'latitude': '32.837527', 'longitude': '-96.69...",13,3,9,18924,3162
6,133,UF2016-1475,38441,511 N AKARD ST,2016-11-26T00:00:00.000,9:00:00 PM,9881,Male,White,2009-06-10T00:00:00.000,...,130,CENTRAL,D14,,"{'latitude': '32.784328', 'longitude': '-96.80...",12,3,14,20152,3162
7,1761,UF2016-0334,33133,4709 LUCKY LN,2016-03-16T00:00:00.000,8:00:00 PM,9058,Female,Black,2007-07-04T00:00:00.000,...,510,NORTHWEST,D6,,"{'latitude': '32.803725', 'longitude': '-96.87...",6,3,6,20162,3162
8,2014,UF2016-0216,33989,300 S LAMAR ST,2016-02-17T00:00:00.000,9:25:00 PM,10381,Male,Hispanic,2012-05-09T00:00:00.000,...,130,CENTRAL,D14,,"{'latitude': '32.778107', 'longitude': '-96.80...",12,3,14,20153,3162
9,19,UF2016-1499,"38840, 38841",18600 DALLAS NORTH TOLLWAY,2016-12-24T00:00:00.000,8:55:00 AM,9705,Male,White,2009-01-07T00:00:00.000,...,610,NORTH CENTRAL,D12,,"{'human_address': '{""address"": ""18600 DALLAS N...",NaN,NaN,NaN,NaN,NaN
10,22,UF2017-063,"38816, 38817",9500 POPPY DR,2016-12-23T00:00:00.000,1:45:00 AM,10066,Male,White,2009-11-11T00:00:00.000,...,230,NORTHEAST,D9,,"{'human_address': '{""address"": ""9500 POPPY DR""...",NaN,NaN,NaN,NaN,NaN
11,23,UF2017-063,"38818, 38819",9500 POPPY DR,2016-12-23T00:00:00.000,1:45:00 AM,10224,Male,White,2010-08-18T00:00:00.000,...,230,NORTHEAST,D9,,"{'human_address': '{""address"": ""9500 POPPY DR""...",NaN,NaN,NaN,NaN,NaN
12,222,UF2016-1303,"37890, 37891, 37892",4600 S MALCOLM X BLVD,2016-11-08T00:00:00.000,2:30:00 AM,9626,Male,American Ind,2008-09-17T00:00:00.000,...,340,SOUTHEAST,D7,Hatcher Scyene*,"{'human_address': '{""address"": ""4600 S MALCOLM...",NaN,NaN,NaN,NaN,NaN
13,283,UF2016-1265,"37656, 37657",10100 L B J FWY,2016-10-23T00:00:00.000,6:00:00 PM,10355,Male,White,2012-05-09T00:00:00.000,...,240,NORTHEAST,D10,,"{'human_address': '{""address"": ""10100 L B J FW...",NaN,NaN,NaN,NaN,NaN
14,284,UF2016-1265,"37685, 37686, 37687",10100 L B J FWY,2016-10-23T00:00:00.000,6:00:00 PM,10334,Male,Hispanic,2012-03-28T00:00:00.000,...,240,NORTHEAST,D10,,"{'human_address': '{""address"": ""10100 L B J FW...",NaN,NaN,NaN,NaN,NaN
15,310,UF2016-1192,37532,9400 L B J FWY,2016-10-18T00:00:00.000,6:30:00 PM,9215,Male,Black,2007-09-05T00:00:00.000,...,250,NORTHEAST,D10,Greenville LBJ*,"{'human_address': '{""address"": ""9400 L B J FWY...",NaN,NaN,NaN,NaN,NaN
16,348,UF2016-1293,"37408, 37409",6897 VALLEY GLEN DR,2016-10-12T00:00:00.000,2:30:00 AM,8517,Female,White,2004-06-04T00:00:00.000,...,230,NORTHEAST,D9,,"{'human_address': '{""address"": ""6897 VALLEY GL...",NaN,NaN,NaN,NaN,NaN
17,362,UF2016-1188,"37378, 37379",2486 MAPLE ROUTH CONN,2016-10-10T00:00:00.000,1:30:00 AM,10701,Male,Black,2013-11-06T00:00:00.000,...,120,CENTRAL,D14,McKinney Allen*,"{'human_address': '{""address"": ""2486 MAPLE ROU...",NaN,NaN,NaN,NaN,NaN
18,582,UF2016-1223,36725,8630 FIRESIDE DR,2016-09-07T00:00:00.000,6:00:00 PM,10372,Male,Black,2012-05-09T00:00:00.000,...,350,SOUTHEAST,D8,,"{'latitude': '32.697895', 'longitude': '-96.67...",8,3,8,18921,3162
19,374,UF2016-1309,"37309, 37310",9200 L B J FWY,2016-10-08T00:00:00.000,4:00:00 AM,10130,Male,White,2010-03-03T00:00:00.000,...,250,NORTHEAST,D10,Greenville LBJ*,"{'human_address': '{""address"": ""9200 L B J FWY...",NaN,NaN,NaN,NaN,NaN
20,375,UF2016-1309,37311,9200 L B J FWY,2016-10-08T00:00:00.000,4:00:00 AM,10870,Male,White,2014-08-13T00:00:00.000,...,250,NORTHEAST,D10,Greenville LBJ*,"{'human_address': '{""address"": ""9200 L B J FWY...",NaN,NaN,NaN,NaN,NaN
21,400,UF2016-1242,"37231, 37232, 37233",4300 S MALCOLM X BLVD,2016-10-03T00:00:00.000,9:00:00 PM,10503,Male,White,2013-04-10T00:00:00.000,...,340,SOUTHEAST,D7,Hatcher Scyene*,"{'human_address': '{""address"": ""4300 S MALCOLM...",NaN,NaN,NaN,NaN,NaN
22,489,UF2016-1156,"36980, 36981, 36982",3315 PARROT ST,2016-09-23T00:00:00.000,6:50:00 PM,11028,Male,White,2015-06-03T00:00:00.000,...,720,SOUTH CENTRAL,D4,,"{'human_address': '{""address"": ""3315 PARROT ST...",NaN,NaN,NaN,NaN,NaN
23,495,UF2016-1120,"36941, 36942",900 WOOD ST,2016-09-21T00:00:00.000,4:32:00 PM,10724,Male,White,2014-01-29T00:00:00.000,...,130,CENTRAL,D2,,"{'human_address': '{""address"": ""900 WOOD ST"", ...",NaN,NaN,NaN,NaN,NaN
24,539,UF2016-1060,36791,8051 L B J FWY,2016-09-13T00:00:00.000,12:25:00 AM,7310,Male,White,1995-11-08T00:00:00.000,...,640,NORTH CENTRAL,D11,Maham SpringValley*,"{'human_address': '{""address"": ""8051 L B J FWY...",NaN,NaN,NaN,NaN,NaN
25,544,UF2016-1060,36776,8051 L B J FWY,2016-09-12T00:00:00.000,12:25:00 AM,8862,Male,Hispanic,2006-06-30T00:00:00.000,...,640,NORTH CENTRAL,D11,Maham SpringValley*,"{'human_address': '{""address"": ""8051 L B J FWY...",NaN,NaN,NaN,NaN,NaN
26,807,UF2016-0896,"35974, 35976",8102 L B J FWY,2016-08-03T00:00:00.000,1:45:00 PM,5806,Male,White,1988-06-16T00:00:00.000,...,640,NORTH CENTRAL,D11,,"{'human_address': '{""address"": ""8102 L B J FWY...",NaN,NaN,NaN,NaN,NaN
27,808,UF2016-0896,"35979, 35980",8102 L B J FWY,2016-08-03T00:00:00.000,1:45:00 PM,5273,Male,White,1985-08-15T00:00:00.000,...,640,NORTH CENTRAL,D11,,"{'human_address': '{""address"": ""8102 L B J FWY...",NaN,NaN,NaN,NaN,NaN
28,809,UF2016-0896,"35977, 35978",8102 L B J FWY,2016-08-03T00:00:00.000,1:45:00 PM,5273,Male,White,1985-08-15T00:00:00.000,...,640,NORTH CENTRAL,D11,,"{'human_address': '{""address"": ""8102 L B J FWY...",NaN,NaN,NaN,NaN,NaN
29,810,UF2016-0896,"35981, 35982",8102 L B J FWY,2016-08-03T00:00:00.000,1:45:00 PM,5806,Male,White,1988-06-16T00:00:00.000,...,640,NORTH CENTRAL,D11,,"{'human_address': '{""address"": ""8102 L B J FWY...",NaN,NaN,NaN,NaN,NaN
30,828,UF2016-1135,36310,4845 ELSIE FAYE HEGGINS ST,2016-07-28T00:00:00.000,11:30:00 PM,10913,Male,White,2014-10-22T00:00:00.000,...,310,SOUTHEAST,D7,Hatcher Scyene*,"{'human_address': '{""address"": ""4845 ELSIE FAY...",NaN,NaN,NaN,NaN,NaN
31,866,UF2016-0806,35734,39690 L B J FWY,2016-07-18T00:00:00.000,1:30:00 PM,5485,Male,Black,1986-09-29T00:00:00.000,...,740,SOUTH CENTRAL,D8,CampWisdom Chaucer*,"{'human_address': '{""address"": ""39690 L B J FW...",NaN,NaN,NaN,NaN,NaN
32,867,UF2016-0806,"35753, 35754",39000 L B J FWY,2016-07-18T00:00:00.000,1:30:00 PM,9649,Male,White,2008-10-29T00:00:00.000,...,740,SOUTH CENTRAL,D8,,"{'human_address': '{""address"": ""39000 L B J FW...",NaN,NaN,NaN,NaN,NaN
33,868,UF2016-0806,35755,39690 L B J FWY,2016-07-18T00:00:00.000,1:30:00 PM,10824,Male,Black,2014-06-18T00:00:00.000,...,740,SOUTH CENTRAL,D8,CampWisdom Chaucer*,"{'human_address': '{""address"": ""39690 L B J FW...",NaN,NaN,NaN,NaN,NaN
34,869,UF2016-0806,35735,39690 L B J FWY,2016-07-18T00:00:00.000,1:30:00 PM,11056,Male,Hispanic,2015-07-29T00:00:00.000,...,740,SOUTH CENTRAL,D8,CampWisdom Chaucer*,"{'human_address': '{""address"": ""39690 L B J FW...",NaN,NaN,NaN,NaN,NaN
35,416,UF2016-1172,37186,5507 BENT TRL,2016-10-01T00:00:00.000,7:00:00 PM,10846,Male,Hispanic,2013-02-06T00:00:00.000,...,620,NORTH CENTRAL,D11,,"{'latitude': '32.976635', 'longitude': '-96.81...",10,3,11,20168,3162
36,870,UF2016-0806,36940,39690 L B J FWY,2016-07-18T00:00:00.000,1:30:00 PM,7993,Male,Black,2001-11-30T00:00:00.000,...,740,SOUTH CENTRAL,D8,CampWisdom Chaucer*,"{'human_address': '{""address"": ""39690 L B J FW...",NaN,NaN,NaN,NaN,NaN
37,872,UF2016-0893,"35760, 35761, 35762, 35763",4600 S MALCOLM X BLVD,2016-07-18T00:00:00.000,11:45:00 PM,10586,Male,Other,2013-06-19T00:00:00.000,...,340,SOUTHEAST,D7,Hatcher Scyene*,"{'human_address': '{""address"": ""4600 S MALCOLM...",NaN,NaN,NaN,NaN,NaN
38,873,UF2016-0893,"35757, 35758, 35759",4600 S MALCOLM X BLVD,2016-07-18T00:00:00.000,11:45:00 PM,10503,Male,White,2013-04-10T00:00:00.000,...,340,SOUTHEAST,D7,Hatcher Scyene*,"{'human_address': '{""address"": ""4600 S MALCOLM...",NaN,NaN,NaN,NaN,NaN
39,874,UF2016-0893,"35897, 35898, 35899, 35900, 35901",4600 S MALCOLM X BLVD,2016-07-18T00:00:00.000,11:45:00 PM,9180,Male,White,2008-05-28T00:00:00.000,...,340,SOUTHEAST,D7,Hatcher Scyene*,"{'human_address': '{""address"": ""4600 S MALCOLM...",NaN,NaN,NaN,NaN,NaN
40,877,UF2016-1010,"35729, 35730, 35731",4848 ELSIE FAYE HEGGINS ST,2016-07-18T00:00:00.000,3:08:00 PM,10322,Male,White,2012-03-28T00:00:00.000,...,310,SOUTHEAST,D7,,"{'human_address': '{""address"": ""4848 ELSIE FAY...",NaN,NaN,NaN,NaN,NaN
41,878,UF2016-1010,35733,4848 ELSIE FAYE HEGGINS ST,2016-07-18T00:00:00.000,3:08:00 PM,6484,Male,Hispanic,1989-03-17T00:00:00.000,...,310,SOUTHEAST,D7,,"{'human_address': '{""address"": ""4848 ELSIE FAY...",NaN,NaN,NaN,NaN,NaN
42,879,UF2016-1010,35728,4848 ELSIE FAYE HEGGINS ST,2016-07-18T00:00:00.000,3:08:00 PM,8799,Male,White,2006-03-29T00:00:00.000,...,310,SOUTHEAST,D7,,"{'human_address': '{""address"": ""4848 ELSIE FAY...",NaN,NaN,NaN,NaN,NaN
43,880,UF2016-1010,35732,4846 ELSIE FAYE HEGGINS ST,2016-07-18T00:00:00.000,3:08:00 PM,9857,Male,White,2009-06-10T00:00:00.000,...,310,SOUTHEAST,D7,,"{'human_address': '{""address"": ""4846 ELSIE FAY...",NaN,NaN,NaN,NaN,NaN
44,1177,UF2016-0637,34793,7909 L B J FWY,2016-06-01T00:00:00.000,6:50:00 PM,9144,Male,Black,2007-05-30T00:00:00.000,...,630,NORTH CENTRAL,D11,Maham SpringValley*,"{'human_address': '{""address"": ""7909 L B J FWY...",NaN,NaN,NaN,NaN,NaN
45,1178,UF2016-0637,34792,7909 L B J FWY,2016-06-01T00:00:00.000,6:50:00 PM,9949,Male,Hispanic,2009-08-19T00:00:00.000,...,630,NORTH CENTRAL,D11,Maham SpringValley*,"{'human_address': '{""address"": ""7909 L B J FWY...",NaN,NaN,NaN,NaN,NaN
46,1196,UF2016-0642,34833,5201 BARNES BRIDGE RD,2016-05-30T00:00:00.000,10:00:00 PM,9654,Male,Black,2008-10-29T00:00:00.000,...,220,NORTHEAST,D9,,"{'human_address': '{""address"": ""5201 BARNES BR...",NaN,NaN,NaN,NaN,NaN
47,1226,UF2016-0677,"34620, 34621, 34622, 34623, 34624",4600 S MALCOLM X BLVD,2016-05-23T00:00:00.000,7:11:00 PM,10969,Male,White,2015-01-28T00:00:00.000,...,340,SOUTHEAST,D7,Hatcher Scyene*,"{'human_address': '{""address"": ""4600 S MALCOLM...",NaN,NaN,NaN,NaN,NaN
48,2336,UF2016-0033,"31428, 31429, 31430",5100 SPUR 408,2016-01-08T00:00:00.000,9:00:00 PM,8287,Male,Hispanic,2002-07-19T00:00:00.000,...,430,SOUTHWEST,D3,,"{'human_address': '{""address"": ""5100 SPUR 408""...",NaN,NaN,NaN,NaN,NaN
49,1228,UF2016-0677,"34615, 34616, 34617, 34618, 34625",4600 S MALCOLM X BLVD,2016-05-23T00:00:00.000,7:11:00 PM,10823,Male,Asian,2014-06-18T00:00:00.000,...,340,SOUTHEAST,D7,Hatcher Scyene*,"{'human_address': '{""address"": ""4600 S MALCOLM...",NaN,NaN,NaN,NaN,NaN

In [50]:
# replace NaN string values with None type for proper load into database
df_2016.replace(to_replace='NaN',value=None,inplace=True)

objectid                       None
filenum                        None
uofnum                         None
address                        None
occurred_d                     None
occurred_t                     None
current_ba                     None
offsex                         None
offrace                        None
hire_dt                        None
off_injure                     None
offcondtyp                     None
off_hospit                     None
service_ty                     None
forcetype                      None
uof_reason                     None
cycles_num                     None
forceeffec                     None
street_n                       None
street                         None
street_g                       None
street_t                       None
citnum                         None
citrace                        None
citsex                         None
cit_injure                     None
citcondtyp                     None
cit_arrest                     None
cit_infl_a                     None
citcharget                     None
ra                             None
beat                           None
sector                         None
division                       None
council_district               None
taag_name                      None
geocoded_column                None
:@computed_region_sjyw_rtbm    None
:@computed_region_2f7u_b5gs    None
:@computed_region_at43_7y52    None
:@computed_region_3qur_xvie    None
:@computed_region_28rh_izyk    None
dtype: object

In [51]:
# cast all empty values into None type
df_2016.where(pd.notnull(df_2016),None,inplace=True)

In [52]:
# convert the geocode column from dict to JSON string for load into database
df_2016['geocoded_column'] = df_2016['geocoded_column'].apply(lambda x:json.dumps(x))

In [53]:
# replace NULL string values with None type for proper load into database
df_2016.replace(to_replace='NULL',inplace=True)

objectid                       None
filenum                        None
uofnum                         None
address                        None
occurred_d                     None
occurred_t                     None
current_ba                     None
offsex                         None
offrace                        None
hire_dt                        None
off_injure                     None
offcondtyp                     None
off_hospit                     None
service_ty                     None
forcetype                      None
uof_reason                     None
cycles_num                     None
forceeffec                     None
street_n                       None
street                         None
street_g                       None
street_t                       None
citnum                         None
citrace                        None
citsex                         None
cit_injure                     None
citcondtyp                     None
cit_arrest                     None
cit_infl_a                     None
citcharget                     None
ra                             None
beat                           None
sector                         None
division                       None
council_district               None
taag_name                      None
geocoded_column                None
:@computed_region_sjyw_rtbm    None
:@computed_region_2f7u_b5gs    None
:@computed_region_at43_7y52    None
:@computed_region_3qur_xvie    None
:@computed_region_28rh_izyk    None
dtype: object

In [54]:
# adding the year reported values
df_2016['year_reported'] = '2016'

In [55]:
df_2016.head(50)

,objectid,filenum,uofnum,address,occurred_d,occurred_t,current_ba,offsex,offrace,hire_dt,...,division,council_district,taag_name,geocoded_column,:@computed_region_sjyw_rtbm,:@computed_region_2f7u_b5gs,:@computed_region_at43_7y52,:@computed_region_3qur_xvie,:@computed_region_28rh_izyk,year_reported
0,609,UF2016-1185,37702,211 N ERVAY ST,2016-09-03T00:00:00.000,4:14:00 AM,10810,Male,Black,2014-05-07T00:00:00.000,...,CENTRAL,D14,,"{""latitude"": ""32.782205"", ""longitude"": ""-96.79...",12,3,14,20152,3162,2016
1,1705,UF2016-0418,33413,7647 FERGUSON RD,2016-03-22T00:00:00.000,11:00:00 PM,7706,Male,White,1999-01-08T00:00:00.000,...,NORTHEAST,D9,Ferguson Highland*,"{""latitude"": ""32.798978"", ""longitude"": ""-96.71...",13,3,9,19361,3162,2016
2,1239,UF2016-0616,34567,716 BIMEBELLA LN,2016-05-22T00:00:00.000,1:29:00 PM,11014,Male,Black,2015-05-20T00:00:00.000,...,SOUTHWEST,D6,,"{""latitude"": ""32.73971"", ""longitude"": ""-96.925...",6,3,6,18528,3162,2016
3,2320,UF2016-1349,31460,5600 L B J FWY,2016-01-10T00:00:00.000,8:55:00 PM,6692,Male,Black,1991-07-29T00:00:00.000,...,NORTH CENTRAL,D11,,"{""human_address"": ""{\""address\"": \""5600 L B J ...",None,None,None,None,None,2016
4,221,UF2016-1303,"37879, 37898",4600 S MALCOLM X BLVD,2016-11-08T00:00:00.000,2:30:00 AM,9844,Male,White,2009-10-04T00:00:00.000,...,SOUTHEAST,D7,Hatcher Scyene*,"{""human_address"": ""{\""address\"": \""4600 S MALC...",None,None,None,None,None,2016
5,549,UF2016-1084,36724,1234 PEAVY RD,2016-09-11T00:00:00.000,7:20:00 PM,9855,Male,White,2009-06-10T00:00:00.000,...,NORTHEAST,D9,,"{""latitude"": ""32.837527"", ""longitude"": ""-96.69...",13,3,9,18924,3162,2016
6,133,UF2016-1475,38441,511 N AKARD ST,2016-11-26T00:00:00.000,9:00:00 PM,9881,Male,White,2009-06-10T00:00:00.000,...,CENTRAL,D14,,"{""latitude"": ""32.784328"", ""longitude"": ""-96.80...",12,3,14,20152,3162,2016
7,1761,UF2016-0334,33133,4709 LUCKY LN,2016-03-16T00:00:00.000,8:00:00 PM,9058,Female,Black,2007-07-04T00:00:00.000,...,NORTHWEST,D6,,"{""latitude"": ""32.803725"", ""longitude"": ""-96.87...",6,3,6,20162,3162,2016
8,2014,UF2016-0216,33989,300 S LAMAR ST,2016-02-17T00:00:00.000,9:25:00 PM,10381,Male,Hispanic,2012-05-09T00:00:00.000,...,CENTRAL,D14,,"{""latitude"": ""32.778107"", ""longitude"": ""-96.80...",12,3,14,20153,3162,2016
9,19,UF2016-1499,"38840, 38841",18600 DALLAS NORTH TOLLWAY,2016-12-24T00:00:00.000,8:55:00 AM,9705,Male,White,2009-01-07T00:00:00.000,...,NORTH CENTRAL,D12,,"{""human_address"": ""{\""address\"": \""18600 DALLA...",None,None,None,None,None,2016
10,22,UF2017-063,"38816, 38817",9500 POPPY DR,2016-12-23T00:00:00.000,1:45:00 AM,10066,Male,White,2009-11-11T00:00:00.000,...,NORTHEAST,D9,,"{""human_address"": ""{\""address\"": \""9500 POPPY ...",None,None,None,None,None,2016
11,23,UF2017-063,"38818, 38819",9500 POPPY DR,2016-12-23T00:00:00.000,1:45:00 AM,10224,Male,White,2010-08-18T00:00:00.000,...,NORTHEAST,D9,,"{""human_address"": ""{\""address\"": \""9500 POPPY ...",None,None,None,None,None,2016
12,222,UF2016-1303,"37890, 37891, 37892",4600 S MALCOLM X BLVD,2016-11-08T00:00:00.000,2:30:00 AM,9626,Male,American Ind,2008-09-17T00:00:00.000,...,SOUTHEAST,D7,Hatcher Scyene*,"{""human_address"": ""{\""address\"": \""4600 S MALC...",None,None,None,None,None,2016
13,283,UF2016-1265,"37656, 37657",10100 L B J FWY,2016-10-23T00:00:00.000,6:00:00 PM,10355,Male,White,2012-05-09T00:00:00.000,...,NORTHEAST,D10,,"{""human_address"": ""{\""address\"": \""10100 L B J...",None,None,None,None,None,2016
14,284,UF2016-1265,"37685, 37686, 37687",10100 L B J FWY,2016-10-23T00:00:00.000,6:00:00 PM,10334,Male,Hispanic,2012-03-28T00:00:00.000,...,NORTHEAST,D10,,"{""human_address"": ""{\""address\"": \""10100 L B J...",None,None,None,None,None,2016
15,310,UF2016-1192,37532,9400 L B J FWY,2016-10-18T00:00:00.000,6:30:00 PM,9215,Male,Black,2007-09-05T00:00:00.000,...,NORTHEAST,D10,Greenville LBJ*,"{""human_address"": ""{\""address\"": \""9400 L B J ...",None,None,None,None,None,2016
16,348,UF2016-1293,"37408, 37409",6897 VALLEY GLEN DR,2016-10-12T00:00:00.000,2:30:00 AM,8517,Female,White,2004-06-04T00:00:00.000,...,NORTHEAST,D9,,"{""human_address"": ""{\""address\"": \""6897 VALLEY...",None,None,None,None,None,2016
17,362,UF2016-1188,"37378, 37379",2486 MAPLE ROUTH CONN,2016-10-10T00:00:00.000,1:30:00 AM,10701,Male,Black,2013-11-06T00:00:00.000,...,CENTRAL,D14,McKinney Allen*,"{""human_address"": ""{\""address\"": \""2486 MAPLE ...",None,None,None,None,None,2016
18,582,UF2016-1223,36725,8630 FIRESIDE DR,2016-09-07T00:00:00.000,6:00:00 PM,10372,Male,Black,2012-05-09T00:00:00.000,...,SOUTHEAST,D8,,"{""latitude"": ""32.697895"", ""longitude"": ""-96.67...",8,3,8,18921,3162,2016
19,374,UF2016-1309,"37309, 37310",9200 L B J FWY,2016-10-08T00:00:00.000,4:00:00 AM,10130,Male,White,2010-03-03T00:00:00.000,...,NORTHEAST,D10,Greenville LBJ*,"{""human_address"": ""{\""address\"": \""9200 L B J ...",None,None,None,None,None,2016
20,375,UF2016-1309,37311,9200 L B J FWY,2016-10-08T00:00:00.000,4:00:00 AM,10870,Male,White,2014-08-13T00:00:00.000,...,NORTHEAST,D10,Greenville LBJ*,"{""human_address"": ""{\""address\"": \""9200 L B J ...",None,None,None,None,None,2016
21,400,UF2016-1242,"37231, 37232, 37233",4300 S MALCOLM X BLVD,2016-10-03T00:00:00.000,9:00:00 PM,10503,Male,White,2013-04-10T00:00:00.000,...,SOUTHEAST,D7,Hatcher Scyene*,"{""human_address"": ""{\""address\"": \""4300 S MALC...",None,None,None,None,None,2016
22,489,UF2016-1156,"36980, 36981, 36982",3315 PARROT ST,2016-09-23T00:00:00.000,6:50:00 PM,11028,Male,White,2015-06-03T00:00:00.000,...,SOUTH CENTRAL,D4,,"{""human_address"": ""{\""address\"": \""3315 PARROT...",None,None,None,None,None,2016
23,495,UF2016-1120,"36941, 36942",900 WOOD ST,2016-09-21T00:00:00.000,4:32:00 PM,10724,Male,White,2014-01-29T00:00:00.000,...,CENTRAL,D2,,"{""human_address"": ""{\""address\"": \""900 WOOD ST...",None,None,None,None,None,2016
24,539,UF2016-1060,36791,8051 L B J FWY,2016-09-13T00:00:00.000,12:25:00 AM,7310,Male,White,1995-11-08T00:00:00.000,...,NORTH CENTRAL,D11,Maham SpringValley*,"{""human_address"": ""{\""address\"": \""8051 L B J ...",None,None,None,None,None,2016
25,544,UF2016-1060,36776,8051 L B J FWY,2016-09-12T00:00:00.000,12:25:00 AM,8862,Male,Hispanic,2006-06-30T00:00:00.000,...,NORTH CENTRAL,D11,Maham SpringValley*,"{""human_address"": ""{\""address\"": \""8051 L B J ...",None,None,None,None,None,2016
26,807,UF2016-0896,"35974, 35976",8102 L B J FWY,2016-08-03T00:00:00.000,1:45:00 PM,5806,Male,White,1988-06-16T00:00:00.000,...,NORTH CENTRAL,D11,,"{""human_address"": ""{\""address\"": \""8102 L B J ...",None,None,None,None,None,2016
27,808,UF2016-0896,"35979, 35980",8102 L B J FWY,2016-08-03T00:00:00.000,1:45:00 PM,5273,Male,White,1985-08-15T00:00:00.000,...,NORTH CENTRAL,D11,,"{""human_address"": ""{\""address\"": \""8102 L B J ...",None,None,None,None,None,2016
28,809,UF2016-0896,"35977, 35978",8102 L B J FWY,2016-08-03T00:00:00.000,1:45:00 PM,5273,Male,White,1985-08-15T00:00:00.000,...,NORTH CENTRAL,D11,,"{""human_address"": ""{\""address\"": \""8102 L B J ...",None,None,None,None,None,2016
29,810,UF2016-0896,"35981, 35982",8102 L B J FWY,2016-08-03T00:00:00.000,1:45:00 PM,5806,Male,White,1988-06-16T00:00:00.000,...,NORTH CENTRAL,D11,,"{""human_address"": ""{\""address\"": \""8102 L B J ...",None,None,None,None,None,2016
30,828,UF2016-1135,36310,4845 ELSIE FAYE HEGGINS ST,2016-07-28T00:00:00.000,11:30:00 PM,10913,Male,White,2014-10-22T00:00:00.000,...,SOUTHEAST,D7,Hatcher Scyene*,"{""human_address"": ""{\""address\"": \""4845 ELSIE ...",None,None,None,None,None,2016
31,866,UF2016-0806,35734,39690 L B J FWY,2016-07-18T00:00:00.000,1:30:00 PM,5485,Male,Black,1986-09-29T00:00:00.000,...,SOUTH CENTRAL,D8,CampWisdom Chaucer*,"{""human_address"": ""{\""address\"": \""39690 L B J...",None,None,None,None,None,2016
32,867,UF2016-0806,"35753, 35754",39000 L B J FWY,2016-07-18T00:00:00.000,1:30:00 PM,9649,Male,White,2008-10-29T00:00:00.000,...,SOUTH CENTRAL,D8,,"{""human_address"": ""{\""address\"": \""39000 L B J...",None,None,None,None,None,2016
33,868,UF2016-0806,35755,39690 L B J FWY,2016-07-18T00:00:00.000,1:30:00 PM,10824,Male,Black,2014-06-18T00:00:00.000,...,SOUTH CENTRAL,D8,CampWisdom Chaucer*,"{""human_address"": ""{\""address\"": \""39690 L B J...",None,None,None,None,None,2016
34,869,UF2016-0806,35735,39690 L B J FWY,2016-07-18T00:00:00.000,1:30:00 PM,11056,Male,Hispanic,2015-07-29T00:00:00.000,...,SOUTH CENTRAL,D8,CampWisdom Chaucer*,"{""human_address"": ""{\""address\"": \""39690 L B J...",None,None,None,None,None,2016
35,416,UF2016-1172,37186,5507 BENT TRL,2016-10-01T00:00:00.000,7:00:00 PM,10846,Male,Hispanic,2013-02-06T00:00:00.000,...,NORTH CENTRAL,D11,,"{""latitude"": ""32.976635"", ""longitude"": ""-96.81...",10,3,11,20168,3162,2016
36,870,UF2016-0806,36940,39690 L B J FWY,2016-07-18T00:00:00.000,1:30:00 PM,7993,Male,Black,2001-11-30T00:00:00.000,...,SOUTH CENTRAL,D8,CampWisdom Chaucer*,"{""human_address"": ""{\""address\"": \""39690 L B J...",None,None,None,None,None,2016
37,872,UF2016-0893,"35760, 35761, 35762, 35763",4600 S MALCOLM X BLVD,2016-07-18T00:00:00.000,11:45:00 PM,10586,Male,Other,2013-06-19T00:00:00.000,...,SOUTHEAST,D7,Hatcher Scyene*,"{""human_address"": ""{\""address\"": \""4600 S MALC...",None,None,None,None,None,2016
38,873,UF2016-0893,"35757, 35758, 35759",4600 S MALCOLM X BLVD,2016-07-18T00:00:00.000,11:45:00 PM,10503,Male,White,2013-04-10T00:00:00.000,...,SOUTHEAST,D7,Hatcher Scyene*,"{""human_address"": ""{\""address\"": \""4600 S MALC...",None,None,None,None,None,2016
39,874,UF2016-0893,"35897, 35898, 35899, 35900, 35901",4600 S MALCOLM X BLVD,2016-07-18T00:00:00.000,11:45:00 PM,9180,Male,White,2008-05-28T00:00:00.000,...,SOUTHEAST,D7,Hatcher Scyene*,"{""human_address"": ""{\""address\"": \""4600 S MALC...",None,None,None,None,None,2016
40,877,UF2016-1010,"35729, 35730, 35731",4848 ELSIE FAYE HEGGINS ST,2016-07-18T00:00:00.000,3:08:00 PM,10322,Male,White,2012-03-28T00:00:00.000,...,SOUTHEAST,D7,,"{""human_address"": ""{\""address\"": \""4848 ELSIE ...",None,None,None,None,None,2016
41,878,UF2016-1010,35733,4848 ELSIE FAYE HEGGINS ST,2016-07-18T00:00:00.000,3:08:00 PM,6484,Male,Hispanic,1989-03-17T00:00:00.000,...,SOUTHEAST,D7,,"{""human_address"": ""{\""address\"": \""4848 ELSIE ...",None,None,None,None,None,2016
42,879,UF2016-1010,35728,4848 ELSIE FAYE HEGGINS ST,2016-07-18T00:00:00.000,3:08:00 PM,8799,Male,White,2006-03-29T00:00:00.000,...,SOUTHEAST,D7,,"{""human_address"": ""{\""address\"": \""4848 ELSIE ...",None,None,None,None,None,2016
43,880,UF2016-1010,35732,4846 ELSIE FAYE HEGGINS ST,2016-07-18T00:00:00.000,3:08:00 PM,9857,Male,White,2009-06-10T00:00:00.000,...,SOUTHEAST,D7,,"{""human_address"": ""{\""address\"": \""4846 ELSIE ...",None,None,None,None,None,2016
44,1177,UF2016-0637,34793,7909 L B J FWY,2016-06-01T00:00:00.000,6:50:00 PM,9144,Male,Black,2007-05-30T00:00:00.000,...,NORTH CENTRAL,D11,Maham SpringValley*,"{""human_address"": ""{\""address\"": \""7909 L B J ...",None,None,None,None,None,2016
45,1178,UF2016-0637,34792,7909 L B J FWY,2016-06-01T00:00:00.000,6:50:00 PM,9949,Male,Hispanic,2009-08-19T00:00:00.000,...,NORTH CENTRAL,D11,Maham SpringValley*,"{""human_address"": ""{\""address\"": \""7909 L B J ...",None,None,None,None,None,2016
46,1196,UF2016-0642,34833,5201 BARNES BRIDGE RD,2016-05-30T00:00:00.000,10:00:00 PM,9654,Male,Black,2008-10-29T00:00:00.000,...,NORTHEAST,D9,,"{""human_address"": ""{\""address\"": \""5201 BARNES...",None,None,None,None,None,2016
47,1226,UF2016-0677,"34620, 34621, 34622, 34623, 34624",4600 S MALCOLM X BLVD,2016-05-23T00:00:00.000,7:11:00 PM,10969,Male,White,2015-01-28T00:00:00.000,...,SOUTHEAST,D7,Hatcher Scyene*,"{""human_address"": ""{\""address\"": \""4600 S MALC...",None,None,None,None,None,2016
48,2336,UF2016-0033,"31428, 31429, 31430",5100 SPUR 408,2016-01-08T00:00:00.000,9:00:00 PM,8287,Male,Hispanic,2002-07-19T00:00:00.000,...,SOUTHWEST,D3,,"{""human_address"": ""{\""address\"": \""5100 SPUR 4...",None,None,None,None,None,2016
49,1228,UF2016-0677,"34615, 34616, 34617, 34618, 34625",4600 S MALCOLM X BLVD,2016-05-23T00:00:00.000,7:11:00 PM,10823,Male,Asian,2014-06-18T00:00:00.000,...,SOUTHEAST,D7,Hatcher Scyene*,"{""human_address"": ""{\""address\"": \""4600 S MALC...",None,None,None,None,None,2016

In [56]:
# load into table
df_2016[[item for item in table_cols if item in df_2016.columns]].to_sql('uof_filenum',engine,schema='cdep',if_exists='append',index=False,method='multi')

## Load 2015 Data

In [57]:
df_2015 = pd.DataFrame(client.get(url_dict['data_2015'], limit=limit))

In [58]:
df_2015.columns

Index(['id', 'filenum', 'occurred_dt', 'occurred_tm', 'current_badge_no',
       'offsex', 'offrace', 'hire_dt', 'off_injured', 'offcondtype',
       'off_hospital', 'service_type', 'uofnum', 'forcetype', 'uof_reason',
       'cycles_num', 'forceeffective', 'citnum', 'citrace', 'citsex',
       'cit_injured', 'citcondtype', 'cit_arrested', 'cit_infl_assmt',
       'citchargetype', 'arc_street', 'ra', 'beat', 'sector', 'division',
       'dist_name', 'geolocation', ':@computed_region_at43_7y52',
       ':@computed_region_3qur_xvie', ':@computed_region_28rh_izyk'],
      dtype='object')

In [59]:
# rename columns
df_2015.rename(columns={'id':'objectid','occurred_dt':'occurred_d', 'occurred_tm':'occurred_t', 'current_badge_no':'current_ba','off_injured':'off_injure','offcondtype':'offcondtyp','off_hospital':'off_hospit','service_type':'service_ty','forceeffective':'forceeffec','cit_injured':'cit_injure','citcondtype':'citcondtyp','cit_arrested':'cit_arrest','cit_infl_assmt':'cit_infl_a','citchargetype':'citcharget','arc_street':'address','dist_name':'council_district','geolocation':'geocoded_column'},inplace=True)

In [60]:
df_2015.head(30)

,objectid,filenum,occurred_d,occurred_t,current_ba,offsex,offrace,hire_dt,off_injure,offcondtyp,...,address,ra,beat,sector,division,council_district,geocoded_column,:@computed_region_at43_7y52,:@computed_region_3qur_xvie,:@computed_region_28rh_izyk
0,62,UF2015-0108,2015-02-10T00:00:00.000,16:00,10757,Male,White,2014-01-29T00:00:00.000,No,No injuries noted or visible,...,2100 Arden Rd/ Lancaster Rd. Rd.,4196,714,710,SOUTH CENTRAL,D4,"{'human_address': '{""address"": ""2100 Arden Rd/...",NaN,NaN,NaN
1,63,UF2015-0108,2015-02-10T00:00:00.000,16:00,8285,Male,White,2002-07-19T00:00:00.000,No,No injuries noted or visible,...,2100 Arden Rd/ Lancaster Rd. Rd.,4196,714,710,SOUTH CENTRAL,D4,"{'human_address': '{""address"": ""2100 Arden Rd/...",NaN,NaN,NaN
2,68,UF2015-0111,2015-02-11T00:00:00.000,15:45,6175,Male,White,1989-11-02T00:00:00.000,No,No injuries noted or visible,...,8700 Walnut Hill Ln.,6061,213,210,NORTHEAST,D10,"{'human_address': '{""address"": ""8700 Walnut Hi...",NaN,NaN,NaN
3,76,UF2015-0117,2015-02-01T00:00:00.000,18:30,10313,Male,White,2012-03-28T00:00:00.000,No,No injuries noted or visible,...,4407 ELSIE FAYE HEGGINS ST,2121,312,310,SOUTHEAST,D7,"{'human_address': '{""address"": ""4407 ELSIE FAY...",NaN,NaN,NaN
4,77,UF2015-0117,2015-02-01T00:00:00.000,18:30,10506,Male,White,2013-04-10T00:00:00.000,No,No injuries noted or visible,...,4407 ELSIE FAYE HEGGINS ST,2121,312,310,SOUTHEAST,D7,"{'human_address': '{""address"": ""4407 ELSIE FAY...",NaN,NaN,NaN
5,125,UF2015-0152,2015-02-24T00:00:00.000,23:40,10282,Male,Black,2010-09-29T00:00:00.000,No,No injuries noted or visible,...,4500 Larue St.,4202,434,430,SOUTHWEST,D3,"{'human_address': '{""address"": ""4500 Larue St....",NaN,NaN,NaN
6,126,UF2015-0152,2015-02-24T00:00:00.000,23:40,8933,Male,White,2006-09-27T00:00:00.000,No,No injuries noted or visible,...,4500 Larue St.,4202,434,430,SOUTHWEST,D3,"{'human_address': '{""address"": ""4500 Larue St....",NaN,NaN,NaN
7,127,UF2015-0152,2015-02-23T00:00:00.000,23:30,10282,Male,Black,2010-09-29T00:00:00.000,No,No injuries noted or visible,...,4500 Larue St.,4202,434,430,SOUTHWEST,D3,"{'human_address': '{""address"": ""4500 Larue St....",NaN,NaN,NaN
8,130,UF2015-0154,2015-02-28T00:00:00.000,18:00,10327,Male,Black,2012-03-28T00:00:00.000,No,No injuries noted or visible,...,9386 L B J FWY,1030,252,250,NORTHEAST,D10,"{'human_address': '{""address"": ""9386 L B J FWY...",NaN,NaN,NaN
9,174,UF2015-0186,2015-02-17T00:00:00.000,14:30,6736,Male,White,1991-08-26T00:00:00.000,No,No injuries noted or visible,...,9229 John Carpenter Frwy.,3098,512,510,NORTHWEST,D6,"{'human_address': '{""address"": ""9229 John Carp...",NaN,NaN,NaN
10,175,UF2015-0186,2015-02-17T00:00:00.000,14:30,6736,Male,White,1991-08-26T00:00:00.000,No,No injuries noted or visible,...,9229 John Carpenter Frwy.,3098,512,510,NORTHWEST,D6,"{'human_address': '{""address"": ""9229 John Carp...",NaN,NaN,NaN
11,176,UF2015-0186,2015-02-17T00:00:00.000,14:30,6736,Male,White,1991-08-26T00:00:00.000,No,No injuries noted or visible,...,9229 John Carpenter Frwy.,3098,512,510,NORTHWEST,D6,"{'human_address': '{""address"": ""9229 John Carp...",NaN,NaN,NaN
12,177,UF2015-0186,2015-02-17T00:00:00.000,17:00,10733,Male,Hispanic,2014-01-29T00:00:00.000,No,No injuries noted or visible,...,9229 John Carpenter Frwy.,3098,512,510,NORTHWEST,D6,"{'human_address': '{""address"": ""9229 John Carp...",NaN,NaN,NaN
13,185,UF2015-0194,2015-01-03T00:00:00.000,14:10,5485,Male,Black,1986-09-29T00:00:00.000,No,No injuries noted or visible,...,3155 W Wheatland Rd.,4381,745,740,SOUTH CENTRAL,D8,"{'latitude': '32.647583', 'longitude': '-96.87...",8,19749,3162
14,216,UF2015-0235,2015-03-22T00:00:00.000,16:30,10714,Male,Hispanic,2013-11-06T00:00:00.000,No,No injuries noted or visible,...,3256 E NANDINA DR. Dr.,4376,755,750,SOUTH CENTRAL,D8,"{'human_address': '{""address"": ""3256 E NANDINA...",NaN,NaN,NaN
15,237,UF2015-0251,2015-03-15T00:00:00.000,5:50,9948,Male,Hispanic,2010-09-29T00:00:00.000,No,No injuries noted or visible,...,10570 Stone Canyon Dr.,1052,653,650,NORTH CENTRAL,D11,"{'human_address': '{""address"": ""10570 Stone Ca...",NaN,NaN,NaN
16,238,UF2015-0253,2015-03-28T00:00:00.000,22:00,8917,Male,White,2006-09-13T00:00:00.000,No,No injuries noted or visible,...,1550 Empire Central,3091,513,510,NORTHWEST,D2,"{'human_address': '{""address"": ""1550 Empire Ce...",NaN,NaN,NaN
17,289,UF2015-0290,2015-01-03T00:00:00.000,18:15,10074,Male,White,2010-01-20T00:00:00.000,No,No injuries noted or visible,...,2800 E R L THORNTON FWY,2092,152,150,CENTRAL,D7,"{'human_address': '{""address"": ""2800 E R L THO...",NaN,NaN,NaN
18,294,UF2015-0295,2015-03-27T00:00:00.000,1:40,10462,Female,White,2012-09-26T00:00:00.000,No,No injuries noted or visible,...,13600 Montfort Rd.,1013,635,630,NORTH CENTRAL,D11,"{'human_address': '{""address"": ""13600 Montfort...",NaN,NaN,NaN
19,295,UF2015-0296,2015-03-11T00:00:00.000,3:00,10849,Male,Hispanic,2014-06-18T00:00:00.000,No,No injuries noted or visible,...,1600 ELSIE FAYE HEGGINS ST,2187,344,340,SOUTHEAST,D7,"{'human_address': '{""address"": ""1600 ELSIE FAY...",NaN,NaN,NaN
20,338,UF2015-0331,2015-01-28T00:00:00.000,2:34,9178,Male,White,2007-07-11T00:00:00.000,No,No injuries noted or visible,...,4151 N FITZHUGH Ave.,2099,115,110,CENTRAL,D7,"{'human_address': '{""address"": ""4151 N FITZHUG...",NaN,NaN,NaN
21,362,UF2015-0352,2015-03-16T00:00:00.000,0:55,10811,Male,White,2014-05-07T00:00:00.000,No,No injuries noted or visible,...,5522 Eastside Ave.,1193,114,110,CENTRAL,D2,"{'human_address': '{""address"": ""5522 Eastside ...",NaN,NaN,NaN
22,378,UF2015-0368,2015-04-01T00:00:00.000,17:45,10333,Male,Hispanic,2012-03-28T00:00:00.000,No,No injuries noted or visible,...,4818 2nd Ave.,2168,313,310,SOUTHEAST,D7,"{'human_address': '{""address"": ""4818 2nd Ave.""...",NaN,NaN,NaN
23,379,UF2015-0368,2015-04-01T00:00:00.000,17:45,10329,Male,Black,2012-03-28T00:00:00.000,No,No injuries noted or visible,...,4818 2nd Ave.,2168,313,310,SOUTHEAST,D7,"{'human_address': '{""address"": ""4818 2nd Ave.""...",NaN,NaN,NaN
24,406,UF2015-0393,2015-04-14T00:00:00.000,21:50,8502,Male,Hispanic,2004-05-26T00:00:00.000,No,No injuries noted or visible,...,4300 DALLAS FT WORTH TURNPIKE,4077,416,410,SOUTHWEST,D6,"{'human_address': '{""address"": ""4300 DALLAS FT...",NaN,NaN,NaN
25,407,UF2015-0393,2015-04-14T00:00:00.000,21:50,7962,Male,White,2000-09-22T00:00:00.000,No,No injuries noted or visible,...,4300 DALLAS FT WORTH TURNPIKE,4077,416,410,SOUTHWEST,D6,"{'human_address': '{""address"": ""4300 DALLAS FT...",NaN,NaN,NaN
26,420,UF2015-0406,2015-04-18T00:00:00.000,21:00,7930,Male,Black,2000-07-07T00:00:00.000,No,No injuries noted or visible,...,3851 MIDWAY RD,6007,614,610,NORTH CENTRAL,D12,"{'human_address': '{""address"": ""3851 MIDWAY RD...",NaN,NaN,NaN
27,424,UF2015-0410,2015-04-15T00:00:00.000,18:30,10308,Male,White,2012-03-28T00:00:00.000,No,No injuries noted or visible,...,900 WOODALL RODGERS Frwy.,2058,131,130,CENTRAL,D14,"{'human_address': '{""address"": ""900 WOODALL RO...",NaN,NaN,NaN
28,475,UF2015-0454,2015-04-26T00:00:00.000,1:55,8782,Male,White,2006-02-10T00:00:00.000,No,No injuries noted or visible,...,15000 L B J FWY,1132,228,220,NORTHEAST,D9,"{'human_address': '{""address"": ""15000 L B J FW...",NaN,NaN,NaN
29,565,UF2015-0060,2015-01-22T00:00:00.000,20:45,10318,Male,White,2012-03-28T00:00:00.000,Yes,Bruise,...,6675 Cedar Ridge Dr.,4401,435,430,SOUTHWEST,D3,"{'human_address': '{""address"": ""6675 Cedar Rid...",NaN,NaN,NaN

In [61]:
# replace NaN string values with None type for proper load into database
df_2015.replace(to_replace='NaN',value=None,inplace=True)

objectid                       None
filenum                        None
occurred_d                     None
occurred_t                     None
current_ba                     None
offsex                         None
offrace                        None
hire_dt                        None
off_injure                     None
offcondtyp                     None
off_hospit                     None
service_ty                     None
uofnum                         None
forcetype                      None
uof_reason                     None
cycles_num                     None
forceeffec                     None
citnum                         None
citrace                        None
citsex                         None
cit_injure                     None
citcondtyp                     None
cit_arrest                     None
cit_infl_a                     None
citcharget                     None
address                        None
ra                             None
beat                           None
sector                         None
division                       None
council_district               None
geocoded_column                None
:@computed_region_at43_7y52    None
:@computed_region_3qur_xvie    None
:@computed_region_28rh_izyk    None
dtype: object

In [62]:
# cast all empty values into None type
df_2015.where(pd.notnull(df_2015),None,inplace=True)

In [63]:
# convert the geocode column from dict to JSON string for load into database
df_2015['geocoded_column'] = df_2015['geocoded_column'].apply(lambda x:json.dumps(x))

In [64]:
# replace NULL string values with None type for proper load into database
df_2015.replace(to_replace='NULL',inplace=True)

objectid                       None
filenum                        None
occurred_d                     None
occurred_t                     None
current_ba                     None
offsex                         None
offrace                        None
hire_dt                        None
off_injure                     None
offcondtyp                     None
off_hospit                     None
service_ty                     None
uofnum                         None
forcetype                      None
uof_reason                     None
cycles_num                     None
forceeffec                     None
citnum                         None
citrace                        None
citsex                         None
cit_injure                     None
citcondtyp                     None
cit_arrest                     None
cit_infl_a                     None
citcharget                     None
address                        None
ra                             None
beat                           None
sector                         None
division                       None
council_district               None
geocoded_column                None
:@computed_region_at43_7y52    None
:@computed_region_3qur_xvie    None
:@computed_region_28rh_izyk    None
dtype: object

In [65]:
# adding the year reported values
df_2015['year_reported'] = '2015'

In [66]:
df_2015.head(30)

,objectid,filenum,occurred_d,occurred_t,current_ba,offsex,offrace,hire_dt,off_injure,offcondtyp,...,ra,beat,sector,division,council_district,geocoded_column,:@computed_region_at43_7y52,:@computed_region_3qur_xvie,:@computed_region_28rh_izyk,year_reported
0,62,UF2015-0108,2015-02-10T00:00:00.000,16:00,10757,Male,White,2014-01-29T00:00:00.000,No,No injuries noted or visible,...,4196,714,710,SOUTH CENTRAL,D4,"{""human_address"": ""{\""address\"": \""2100 Arden ...",None,None,None,2015
1,63,UF2015-0108,2015-02-10T00:00:00.000,16:00,8285,Male,White,2002-07-19T00:00:00.000,No,No injuries noted or visible,...,4196,714,710,SOUTH CENTRAL,D4,"{""human_address"": ""{\""address\"": \""2100 Arden ...",None,None,None,2015
2,68,UF2015-0111,2015-02-11T00:00:00.000,15:45,6175,Male,White,1989-11-02T00:00:00.000,No,No injuries noted or visible,...,6061,213,210,NORTHEAST,D10,"{""human_address"": ""{\""address\"": \""8700 Walnut...",None,None,None,2015
3,76,UF2015-0117,2015-02-01T00:00:00.000,18:30,10313,Male,White,2012-03-28T00:00:00.000,No,No injuries noted or visible,...,2121,312,310,SOUTHEAST,D7,"{""human_address"": ""{\""address\"": \""4407 ELSIE ...",None,None,None,2015
4,77,UF2015-0117,2015-02-01T00:00:00.000,18:30,10506,Male,White,2013-04-10T00:00:00.000,No,No injuries noted or visible,...,2121,312,310,SOUTHEAST,D7,"{""human_address"": ""{\""address\"": \""4407 ELSIE ...",None,None,None,2015
5,125,UF2015-0152,2015-02-24T00:00:00.000,23:40,10282,Male,Black,2010-09-29T00:00:00.000,No,No injuries noted or visible,...,4202,434,430,SOUTHWEST,D3,"{""human_address"": ""{\""address\"": \""4500 Larue ...",None,None,None,2015
6,126,UF2015-0152,2015-02-24T00:00:00.000,23:40,8933,Male,White,2006-09-27T00:00:00.000,No,No injuries noted or visible,...,4202,434,430,SOUTHWEST,D3,"{""human_address"": ""{\""address\"": \""4500 Larue ...",None,None,None,2015
7,127,UF2015-0152,2015-02-23T00:00:00.000,23:30,10282,Male,Black,2010-09-29T00:00:00.000,No,No injuries noted or visible,...,4202,434,430,SOUTHWEST,D3,"{""human_address"": ""{\""address\"": \""4500 Larue ...",None,None,None,2015
8,130,UF2015-0154,2015-02-28T00:00:00.000,18:00,10327,Male,Black,2012-03-28T00:00:00.000,No,No injuries noted or visible,...,1030,252,250,NORTHEAST,D10,"{""human_address"": ""{\""address\"": \""9386 L B J ...",None,None,None,2015
9,174,UF2015-0186,2015-02-17T00:00:00.000,14:30,6736,Male,White,1991-08-26T00:00:00.000,No,No injuries noted or visible,...,3098,512,510,NORTHWEST,D6,"{""human_address"": ""{\""address\"": \""9229 John C...",None,None,None,2015
10,175,UF2015-0186,2015-02-17T00:00:00.000,14:30,6736,Male,White,1991-08-26T00:00:00.000,No,No injuries noted or visible,...,3098,512,510,NORTHWEST,D6,"{""human_address"": ""{\""address\"": \""9229 John C...",None,None,None,2015
11,176,UF2015-0186,2015-02-17T00:00:00.000,14:30,6736,Male,White,1991-08-26T00:00:00.000,No,No injuries noted or visible,...,3098,512,510,NORTHWEST,D6,"{""human_address"": ""{\""address\"": \""9229 John C...",None,None,None,2015
12,177,UF2015-0186,2015-02-17T00:00:00.000,17:00,10733,Male,Hispanic,2014-01-29T00:00:00.000,No,No injuries noted or visible,...,3098,512,510,NORTHWEST,D6,"{""human_address"": ""{\""address\"": \""9229 John C...",None,None,None,2015
13,185,UF2015-0194,2015-01-03T00:00:00.000,14:10,5485,Male,Black,1986-09-29T00:00:00.000,No,No injuries noted or visible,...,4381,745,740,SOUTH CENTRAL,D8,"{""latitude"": ""32.647583"", ""longitude"": ""-96.87...",8,19749,3162,2015
14,216,UF2015-0235,2015-03-22T00:00:00.000,16:30,10714,Male,Hispanic,2013-11-06T00:00:00.000,No,No injuries noted or visible,...,4376,755,750,SOUTH CENTRAL,D8,"{""human_address"": ""{\""address\"": \""3256 E NAND...",None,None,None,2015
15,237,UF2015-0251,2015-03-15T00:00:00.000,5:50,9948,Male,Hispanic,2010-09-29T00:00:00.000,No,No injuries noted or visible,...,1052,653,650,NORTH CENTRAL,D11,"{""human_address"": ""{\""address\"": \""10570 Stone...",None,None,None,2015
16,238,UF2015-0253,2015-03-28T00:00:00.000,22:00,8917,Male,White,2006-09-13T00:00:00.000,No,No injuries noted or visible,...,3091,513,510,NORTHWEST,D2,"{""human_address"": ""{\""address\"": \""1550 Empire...",None,None,None,2015
17,289,UF2015-0290,2015-01-03T00:00:00.000,18:15,10074,Male,White,2010-01-20T00:00:00.000,No,No injuries noted or visible,...,2092,152,150,CENTRAL,D7,"{""human_address"": ""{\""address\"": \""2800 E R L ...",None,None,None,2015
18,294,UF2015-0295,2015-03-27T00:00:00.000,1:40,10462,Female,White,2012-09-26T00:00:00.000,No,No injuries noted or visible,...,1013,635,630,NORTH CENTRAL,D11,"{""human_address"": ""{\""address\"": \""13600 Montf...",None,None,None,2015
19,295,UF2015-0296,2015-03-11T00:00:00.000,3:00,10849,Male,Hispanic,2014-06-18T00:00:00.000,No,No injuries noted or visible,...,2187,344,340,SOUTHEAST,D7,"{""human_address"": ""{\""address\"": \""1600 ELSIE ...",None,None,None,2015
20,338,UF2015-0331,2015-01-28T00:00:00.000,2:34,9178,Male,White,2007-07-11T00:00:00.000,No,No injuries noted or visible,...,2099,115,110,CENTRAL,D7,"{""human_address"": ""{\""address\"": \""4151 N FITZ...",None,None,None,2015
21,362,UF2015-0352,2015-03-16T00:00:00.000,0:55,10811,Male,White,2014-05-07T00:00:00.000,No,No injuries noted or visible,...,1193,114,110,CENTRAL,D2,"{""human_address"": ""{\""address\"": \""5522 Eastsi...",None,None,None,2015
22,378,UF2015-0368,2015-04-01T00:00:00.000,17:45,10333,Male,Hispanic,2012-03-28T00:00:00.000,No,No injuries noted or visible,...,2168,313,310,SOUTHEAST,D7,"{""human_address"": ""{\""address\"": \""4818 2nd Av...",None,None,None,2015
23,379,UF2015-0368,2015-04-01T00:00:00.000,17:45,10329,Male,Black,2012-03-28T00:00:00.000,No,No injuries noted or visible,...,2168,313,310,SOUTHEAST,D7,"{""human_address"": ""{\""address\"": \""4818 2nd Av...",None,None,None,2015
24,406,UF2015-0393,2015-04-14T00:00:00.000,21:50,8502,Male,Hispanic,2004-05-26T00:00:00.000,No,No injuries noted or visible,...,4077,416,410,SOUTHWEST,D6,"{""human_address"": ""{\""address\"": \""4300 DALLAS...",None,None,None,2015
25,407,UF2015-0393,2015-04-14T00:00:00.000,21:50,7962,Male,White,2000-09-22T00:00:00.000,No,No injuries noted or visible,...,4077,416,410,SOUTHWEST,D6,"{""human_address"": ""{\""address\"": \""4300 DALLAS...",None,None,None,2015
26,420,UF2015-0406,2015-04-18T00:00:00.000,21:00,7930,Male,Black,2000-07-07T00:00:00.000,No,No injuries noted or visible,...,6007,614,610,NORTH CENTRAL,D12,"{""human_address"": ""{\""address\"": \""3851 MIDWAY...",None,None,None,2015
27,424,UF2015-0410,2015-04-15T00:00:00.000,18:30,10308,Male,White,2012-03-28T00:00:00.000,No,No injuries noted or visible,...,2058,131,130,CENTRAL,D14,"{""human_address"": ""{\""address\"": \""900 WOODALL...",None,None,None,2015
28,475,UF2015-0454,2015-04-26T00:00:00.000,1:55,8782,Male,White,2006-02-10T00:00:00.000,No,No injuries noted or visible,...,1132,228,220,NORTHEAST,D9,"{""human_address"": ""{\""address\"": \""15000 L B J...",None,None,None,2015
29,565,UF2015-0060,2015-01-22T00:00:00.000,20:45,10318,Male,White,2012-03-28T00:00:00.000,Yes,Bruise,...,4401,435,430,SOUTHWEST,D3,"{""human_address"": ""{\""address\"": \""6675 Cedar ...",None,None,None,2015

In [67]:
# load into table
df_2015[[item for item in table_cols if item in df_2015.columns]].to_sql('uof_filenum',engine,schema='cdep',if_exists='append',index=False,method='multi')

## Load 2014 Data

In [68]:
df_2014 = pd.DataFrame(client.get(url_dict['data_2014'], limit=limit))

In [69]:
df_2014.columns

Index(['objectid', 'filenum', 'occurred_d', 'occurred_tm', 'current_ba',
       'offsex', 'offrace', 'hire_dt', 'off_injure', 'offcondtyp',
       'off_hospit', 'service_ty', 'uofnum', 'forcetype', 'uof_reason',
       'cycles_num', 'forceeffec', 'citnum', 'citrace', 'citsex', 'cit_injure',
       'citcondtyp', 'cit_arrest', 'cit_infl_a', 'citcharget', 'arc_street',
       'ra', 'beat', 'sector', 'division', 'dist_name'],
      dtype='object')

In [70]:
# rename columns
df_2014.rename(columns={'occurred_tm':'occurred_t','arc_street':'address','dist_name':'council_district'},inplace=True)

In [71]:
df_2014.head(30)

,objectid,filenum,occurred_d,occurred_t,current_ba,offsex,offrace,hire_dt,off_injure,offcondtyp,...,citcondtyp,cit_arrest,cit_infl_a,citcharget,address,ra,beat,sector,division,council_district
0,1,UF2014-1864,2014-12-31T00:00:00.000,22:56,8912,Male,White,2006-09-13T00:00:00.000,No,No injuries noted or visible,...,No injuries noted or visible,Yes,Unknown,"Assault/FV, Warrant/Hold",1238 N MASTERS DR,2206,335,330,SOUTHEAST,D5
1,2,UF2014-1864,2014-12-31T00:00:00.000,0:45,10759,Male,White,2014-03-12T00:00:00.000,No,No injuries noted or visible,...,No injuries noted or visible,Yes,Unknown,"Assault/FV, Warrant/Hold",1238 N MASTERS DR,2206,335,330,SOUTHEAST,D5
2,3,UF2014-1864,2014-12-31T00:00:00.000,0:45,7523,Female,White,2003-03-20T00:00:00.000,No,No injuries noted or visible,...,No injuries noted or visible,Yes,Unknown,"Assault/FV, Warrant/Hold",1238 N MASTERS DR,2206,335,330,SOUTHEAST,D5
3,4,UF2015-0002,2014-12-31T00:00:00.000,0:52,10694,Male,Black,2013-11-06T00:00:00.000,No,No injuries noted or visible,...,No injuries noted or visible,Yes,Mentally unstable,APOWW,3287 S POLK ST,4262,454,450,SOUTHWEST,D4
4,5,UF2014-1865,2014-12-31T00:00:00.000,0:45,10144,Male,White,2010-03-03T00:00:00.000,No,No injuries noted or visible,...,No injuries noted or visible,Yes,None detected,Warrant/Hold,5200 BEXAR ST,2189,348,340,SOUTHEAST,D7
5,6,UF2014-1898,2014-12-31T00:00:00.000,23:00,9592,Female,White,2008-09-03T00:00:00.000,No,No injuries noted or visible,...,No injuries noted or visible,Yes,Alchohol and unknown drugs,Public Intoxication,7720 MCCALLUM BLVD,6009,623,620,NORTH CENTRAL,D12
6,7,UF2015-0078,2014-12-31T00:00:00.000,16:20,10640,Male,White,2013-09-25T00:00:00.000,No,No injuries noted or visible,...,No injuries noted or visible,Yes,Alchohol and unknown drugs,Public Intoxication,7720 MCCALLUM BLVD,6009,623,620,NORTH CENTRAL,D12
7,8,UF2015-0078,2014-12-31T00:00:00.000,23:20,10640,Male,White,2013-09-25T00:00:00.000,No,No injuries noted or visible,...,No injuries noted or visible,Yes,Alchohol and unknown drugs,Public Intoxication,7720 MCCALLUM BLVD,6009,623,620,NORTH CENTRAL,D12
8,9,UF2015-0078,2014-12-31T00:00:00.000,23:20,10156,Male,Asian,2010-03-03T00:00:00.000,No,No injuries noted or visible,...,No injuries noted or visible,Yes,Alchohol and unknown drugs,Public Intoxication,7720 MCCALLUM BLVD,6009,623,620,NORTH CENTRAL,D12
9,10,UF2014-1893,2014-12-30T00:00:00.000,2:30,10578,Male,Hispanic,2013-06-19T00:00:00.000,No,No injuries noted or visible,...,No injuries noted or visible,Yes,NULL,Criminal Mischief,500 HAVERHILL LN,2204,334,330,SOUTHEAST,D5
10,11,UF2014-1964,2014-12-29T00:00:00.000,0:45,8773,Male,White,2006-01-25T00:00:00.000,No,No injuries noted or visible,...,Injured prior to contact,Yes,Alchohol,Public Intoxication,2700 N FITZHUGH AVE,1159,143,140,CENTRAL,D2
11,12,UF2014-1863,2014-12-29T00:00:00.000,3:15,9502,Male,Hispanic,2008-06-25T00:00:00.000,No,No injuries noted or visible,...,No injuries noted or visible,Yes,FD-Unknown if Armed,"Other Felony Arrest, Other Misdemeanor Arrest...",7021 WOFFORD DR,1235,321,320,SOUTHEAST,D5
12,13,UF2014-1861,2014-12-29T00:00:00.000,20:50,10507,Male,White,2013-04-10T00:00:00.000,No,No injuries noted or visible,...,Abrasion/Scrape,Yes,NULL,No Arrest,900 SAN JACINTO ST,2049,132,130,CENTRAL,D14
13,14,UF2014-1869,2014-12-28T00:00:00.000,2:18,10294,Male,Hispanic,2011-05-11T00:00:00.000,No,No injuries noted or visible,...,Laceration/Cut,Yes,None detected,"DWLI, Traffic Violation, Evading Arrest",11122 ITASCA PL,1129,226,220,NORTHEAST,D9
14,15,UF2014-1869,2014-12-28T00:00:00.000,22:54,10510,Male,Black,2013-04-10T00:00:00.000,No,No injuries noted or visible,...,Puncture,Yes,None detected,"Evading Arrest, DWLS, Traffic Violation",11122 ITASCA PL,1129,226,220,NORTHEAST,D9
15,16,UF2014-1904,2014-12-28T00:00:00.000,4:00,9367,Male,Black,2008-02-06T00:00:00.000,No,No injuries noted or visible,...,No injuries noted or visible,Yes,Unknown Drugs,"Drug Possession - Misdemeanor, Other Misdemea...",2300 W NORTHWEST HWY,4451,521,520,NORTHWEST,D6
16,17,UF2014-1904,2014-12-28T00:00:00.000,4:00,9367,Male,Black,2008-02-06T00:00:00.000,No,No injuries noted or visible,...,No injuries noted or visible,Yes,Unknown Drugs,Warrant/Hold,2300 W NORTHWEST HWY,4451,521,520,NORTHWEST,D6
17,18,UF2014-1904,2014-12-28T00:00:00.000,2:30,10643,Male,Hispanic,2013-09-25T00:00:00.000,No,No injuries noted or visible,...,No injuries noted or visible,Yes,Marijuana,"Drug Possession - Misdemeanor, Other Felony A...",2300 W NORTHWEST HWY,4451,521,520,NORTHWEST,D6
18,19,UF2014-1901,2014-12-28T00:00:00.000,18:07,10482,Male,White,2012-09-26T00:00:00.000,No,No injuries noted or visible,...,No injuries noted or visible,Yes,NULL,"Warrant/Hold, Resisting Search and Transport",2500 W LEDBETTER DR,4315,456,450,SOUTHWEST,D3
19,20,UF2014-1890,2014-12-28T00:00:00.000,13:50,8655,Male,White,2005-05-20T00:00:00.000,No,No injuries noted or visible,...,No injuries noted or visible,Yes,Alchohol and unknown drugs,Assault/FV,2700 ELM ST,2066,153,150,CENTRAL,D2
20,21,UF2014-1892,2014-12-28T00:00:00.000,10:45,7313,Male,Hispanic,1995-11-29T00:00:00.000,No,No injuries noted or visible,...,Non-Visible Injury/Pain,No,Alchohol,No Arrest,601 N EWING AVE,4100,411,410,SOUTHWEST,D1
21,22,UF2014-1956,2014-12-28T00:00:00.000,7:00,10408,Male,Black,2012-06-20T00:00:00.000,No,No injuries noted or visible,...,No injuries noted or visible,No,Unknown,No Arrest,708 W MOCKINGBIRD LN,3111,515,510,NORTHWEST,D6
22,23,UF2014-1956,2014-12-28T00:00:00.000,21:11,10408,Male,Black,2012-06-20T00:00:00.000,No,No injuries noted or visible,...,No injuries noted or visible,No,Unknown,No Arrest,708 W MOCKINGBIRD LN,3111,515,510,NORTHWEST,D6
23,24,UF2014-1901,2014-12-28T00:00:00.000,19:45,10479,Female,White,2012-09-26T00:00:00.000,No,No injuries noted or visible,...,No injuries noted or visible,Yes,None detected,"Warrant/Hold, Resisting Search and Transport",8100 CHRYSALIS DR,4360,744,740,SOUTH CENTRAL,D8
24,25,UF2014-1901,2014-12-28T00:00:00.000,19:45,9894,Male,White,2012-03-28T00:00:00.000,No,No injuries noted or visible,...,No injuries noted or visible,Yes,None detected,"Warrant/Hold, Escape",8100 CHRYSALIS DR,4360,744,740,SOUTH CENTRAL,D8
25,26,UF2014-1901,2014-12-28T00:00:00.000,19:45,10485,Male,White,2012-09-26T00:00:00.000,No,No injuries noted or visible,...,No injuries noted or visible,Yes,None detected,"Warrant/Hold, Escape",8100 CHRYSALIS DR,4360,744,740,SOUTH CENTRAL,D8
26,27,UF2014-2002,2014-12-28T00:00:00.000,0:30,10456,Female,White,2012-09-26T00:00:00.000,No,No injuries noted or visible,...,No injuries noted or visible,Yes,Alchohol and unknown drugs,Public Intoxication,8303 E R L THORNTON FWY,1204,238,230,NORTHEAST,D7
27,28,UF2014-1862,2014-12-27T00:00:00.000,23:05,10254,Male,White,2010-09-29T00:00:00.000,No,No injuries noted or visible,...,No injuries noted or visible,Yes,None detected,"Theft, Evading Arrest",1200 ELLENWOOD DR,2223,355,350,SOUTHEAST,D8
28,29,UF2014-1915,2014-12-27T00:00:00.000,18:45,9250,Male,White,2007-09-26T00:00:00.000,No,No injuries noted or visible,...,No injuries noted or visible,Yes,Mentally unstable,APOWW,6011 LEMMON AVE,3094,542,540,NORTHWEST,D2
29,30,UF2014-1915,2014-12-27T00:00:00.000,14:00,7293,Male,Hispanic,1995-09-22T00:00:00.000,No,No injuries noted or visible,...,"Taser Burn Marks, Treated by DFD",Yes,Unknown Drugs,APOWW,6011 LEMMON AVE,3094,542,540,NORTHWEST,D2

In [72]:
# replace NaN string values with None type for proper load into database
df_2014.replace(to_replace='NaN',inplace=True)

objectid            None
filenum             None
occurred_d          None
occurred_t          None
current_ba          None
offsex              None
offrace             None
hire_dt             None
off_injure          None
offcondtyp          None
off_hospit          None
service_ty          None
uofnum              None
forcetype           None
uof_reason          None
cycles_num          None
forceeffec          None
citnum              None
citrace             None
citsex              None
cit_injure          None
citcondtyp          None
cit_arrest          None
cit_infl_a          None
citcharget          None
address             None
ra                  None
beat                None
sector              None
division            None
council_district    None
dtype: object

In [73]:
# cast all empty values into None type
df_2014.where(pd.notnull(df_2014),None,inplace=True)

In [74]:
# replace NULL string values with None type for proper load into database
df_2014.replace(to_replace='NULL',inplace=True)

objectid            None
filenum             None
occurred_d          None
occurred_t          None
current_ba          None
offsex              None
offrace             None
hire_dt             None
off_injure          None
offcondtyp          None
off_hospit          None
service_ty          None
uofnum              None
forcetype           None
uof_reason          None
cycles_num          None
forceeffec          None
citnum              None
citrace             None
citsex              None
cit_injure          None
citcondtyp          None
cit_arrest          None
cit_infl_a          None
citcharget          None
address             None
ra                  None
beat                None
sector              None
division            None
council_district    None
dtype: object

In [75]:
# adding the year reported values
df_2014['year_reported'] = '2014'

In [76]:
# load into table
df_2014[[item for item in table_cols if item in df_2014.columns]].dropna(thresh=30).to_sql('uof_filenum',engine,schema='cdep',if_exists='append',index=False,method='multi')

## Load 2013 Data

In [77]:
df_2013 = pd.DataFrame(client.get(url_dict['data_2013'], limit=limit))

In [78]:
df_2013.columns

Index(['objectid', 'filenum', 'uofnum', 'match_addr', 'occurred_d',
       'occurred_t', 'current_ba', 'offsex', 'offrace', 'hire_dt',
       'off_injure', 'offcondtyp', 'off_hospit', 'service_ty', 'forcetype',
       'uof_reason', 'cycles_num', 'forceeffec', 'street_n', 'street',
       'street_g', 'street_t', 'address', 'citnum', 'citrace', 'citsex',
       'cit_injure', 'citcondtyp', 'cit_arrest', 'cit_infl_a', 'citcharget',
       'ra', 'beat', 'sector', 'division', 'dist_name', 'taag_name', 'x', 'y',
       'geolocation', ':@computed_region_at43_7y52',
       ':@computed_region_3qur_xvie', ':@computed_region_28rh_izyk'],
      dtype='object')

In [79]:
df_2013.head(30)

,objectid,filenum,uofnum,match_addr,occurred_d,occurred_t,current_ba,offsex,offrace,hire_dt,...,sector,division,dist_name,taag_name,x,y,geolocation,:@computed_region_at43_7y52,:@computed_region_3qur_xvie,:@computed_region_28rh_izyk
0,51,UF2013-00121,"2030, 2034",4600 S MALCOLM X BLVD,2013-01-09T00:00:00.000,21:00,10018,Male,White,2009-09-30T00:00:00.000,...,340,SOUTHEAST,D7,Central CFHawn,2505343.37073000000,6962661.13331000000,"{'human_address': '{""address"": ""4600 S MALCOLM...",NaN,NaN,NaN
1,52,UF2013-00121,"2041, 2042",4600 S MALCOLM X BLVD,2013-01-09T00:00:00.000,21:00,10116,Male,White,2010-01-20T00:00:00.000,...,340,SOUTHEAST,D7,Central CFHawn,2505343.37073000000,6962661.13331000000,"{'human_address': '{""address"": ""4600 S MALCOLM...",NaN,NaN,NaN
2,3061,UF2013-02233,12045,3839 S FITZHUGH AVE,2013-10-27T00:00:00.000,23:30,5118,Male,White,1984-11-28T00:00:00.000,...,110,CENTRAL,D7,NaN,2504798.67034000000,6969124.88107000000,"{'latitude': '32.77433', 'longitude': '-96.754...",7,18524,3162
3,120,UF2013-00212,"3195, 3196",1700 S CESAR CHAVEZ BLVD,2013-02-04T00:00:00.000,21:45,8747,Female,White,2005-12-16T00:00:00.000,...,150,CENTRAL,D2,NaN,2495720.74048000000,6969057.26971000000,"{'human_address': '{""address"": ""1700 S CESAR C...",NaN,NaN,NaN
4,131,UF2013-00227,13590,8300 L B J SERV S,2013-02-06T00:00:00.000,15:00,9222,Male,White,2007-09-05T00:00:00.000,...,250,NORTHEAST,D10,NaN,2501991.75000000000,7023278.88488000000,"{'human_address': '{""address"": ""8300 L B J SER...",NaN,NaN,NaN
5,137,UF2013-00231,"2837, 2838, 2839, 2840",6500 S CENTRAL EXPY,2013-01-28T00:00:00.000,19:45,9997,Male,Other,2009-09-30T00:00:00.000,...,340,SOUTHEAST,D7,NaN,2504175.35740000000,6952684.54824000000,"{'human_address': '{""address"": ""6500 S CENTRAL...",NaN,NaN,NaN
6,151,UF2013-00243,"3446, 3905",3600 OAK GROVE AVE,2013-02-09T00:00:00.000,20:05,9266,Male,Hispanic,2007-09-26T00:00:00.000,...,120,CENTRAL,D14,Ross Bennett,2492013.90082000000,6980260.20744000000,"{'human_address': '{""address"": ""3600 OAK GROVE...",NaN,NaN,NaN
7,248,UF2013-00355,7876,6500 JULIUS SCHEPPS FWY,2013-02-24T00:00:00.000,19:50,9000,Male,Hispanic,2006-11-15T00:00:00.000,...,710,SOUTH CENTRAL,D7,NaN,2502439.97052000000,6952770.76314000000,"{'human_address': '{""address"": ""6500 JULIUS SC...",NaN,NaN,NaN
8,424,UF2013-00522,5227,1419 BIG TOWN BLVD,2013-02-27T00:00:00.000,18:30,8687,Male,White,2005-08-05T00:00:00.000,...,320,SOUTHEAST,D7,NaN,2531429.64322000000,6972870.23930000000,"{'human_address': '{""address"": ""1419 BIG TOWN ...",NaN,NaN,NaN
9,514,UF2013-00623,"3099, 3101",9959 ADLETA BLVD,2013-02-03T00:00:00.000,4:55,10210,Male,White,2010-06-09T00:00:00.000,...,250,NORTHEAST,D10,Forest Audelia,2517112.38673000000,7015120.47541000000,"{'latitude': '32.900662', 'longitude': '-96.71...",10,19761,3162
10,535,UF2013-00645,"5321, 5322",9351 L B J FWY,2013-03-27T00:00:00.000,22:15,8825,Male,White,2006-04-21T00:00:00.000,...,250,NORTHEAST,D10,Greenville LBJ,2509756.44838000000,7019295.48963000000,"{'latitude': '32.910784', 'longitude': '-96.73...",10,19761,3162
11,530,UF2013-00645,5317,9351 L B J FWY,2013-03-27T00:00:00.000,22:15,9808,Male,White,2009-04-15T00:00:00.000,...,250,NORTHEAST,D10,Greenville LBJ,2509756.44838000000,7019295.48963000000,"{'latitude': '32.910784', 'longitude': '-96.73...",10,19761,3162
12,539,UF2013-00654,10501,3300 S R L THORNTON FWY,2013-04-13T00:00:00.000,20:00,10225,Male,White,2010-08-18T00:00:00.000,...,720,SOUTH CENTRAL,D4,RLT Overton+,2483028.88518000000,6943753.84639000000,"{'human_address': '{""address"": ""3300 S R L THO...",NaN,NaN,NaN
13,540,UF2013-00654,5905,3300 S R L THORNTON FWY,2013-04-13T00:00:00.000,19:47,9960,Male,Black,2009-08-19T00:00:00.000,...,720,SOUTH CENTRAL,D4,RLT Overton+,2483028.88518000000,6943753.84639000000,"{'human_address': '{""address"": ""3300 S R L THO...",NaN,NaN,NaN
14,541,UF2013-00654,5906,3300 E R L THORNTON FWY,2013-04-13T00:00:00.000,20:00,9334,Male,White,2008-01-09T00:00:00.000,...,340,SOUTHEAST,D7,NaN,2499244.77845000000,6971242.91414000000,"{'human_address': '{""address"": ""3300 E R L THO...",NaN,NaN,NaN
15,542,UF2013-00654,"5907, 5908",3300 E R L THORNTON FWY,2013-04-13T00:00:00.000,20:00,10432,Female,Hispanic,2012-06-20T00:00:00.000,...,340,SOUTHEAST,D7,NaN,2499244.77845000000,6971242.91414000000,"{'human_address': '{""address"": ""3300 E R L THO...",NaN,NaN,NaN
16,543,UF2013-00654,5909,3300 S R L THORNTON FWY,2013-04-13T00:00:00.000,20:00,10432,Female,Hispanic,2012-06-20T00:00:00.000,...,720,SOUTH CENTRAL,D4,RLT Overton+,2483028.88518000000,6943753.84639000000,"{'human_address': '{""address"": ""3300 S R L THO...",NaN,NaN,NaN
17,544,UF2013-00654,5910,3300 S R L THORNTON FWY,2013-04-13T00:00:00.000,20:00,9334,Male,White,2008-01-09T00:00:00.000,...,720,SOUTH CENTRAL,D4,RLT Overton+,2483028.88518000000,6943753.84639000000,"{'human_address': '{""address"": ""3300 S R L THO...",NaN,NaN,NaN
18,545,UF2013-00654,5911,3300 E R L THORNTON FWY,2013-04-13T00:00:00.000,20:00,9926,Male,Black,2009-08-19T00:00:00.000,...,340,SOUTHEAST,D7,NaN,2499244.77845000000,6971242.91414000000,"{'human_address': '{""address"": ""3300 E R L THO...",NaN,NaN,NaN
19,546,UF2013-00654,7439,3300 E R L THORNTON FWY,2013-04-13T00:00:00.000,20:00,10225,Male,White,2010-08-18T00:00:00.000,...,340,SOUTHEAST,D7,NaN,2499244.77845000000,6971242.91414000000,"{'human_address': '{""address"": ""3300 E R L THO...",NaN,NaN,NaN
20,547,UF2013-00654,7440,3300 E R L THORNTON FWY,2013-04-13T00:00:00.000,20:00,9000,Male,Hispanic,2006-11-15T00:00:00.000,...,340,SOUTHEAST,D7,NaN,2499244.77845000000,6971242.91414000000,"{'human_address': '{""address"": ""3300 E R L THO...",NaN,NaN,NaN
21,548,UF2013-00654,7441,3300 E R L THORNTON FWY,2013-04-13T00:00:00.000,20:00,9960,Male,Black,2009-08-19T00:00:00.000,...,340,SOUTHEAST,D7,NaN,2499244.77845000000,6971242.91414000000,"{'human_address': '{""address"": ""3300 E R L THO...",NaN,NaN,NaN
22,573,UF2013-00687,5600,2951 TALISMAN DR,2013-01-08T00:00:00.000,21:00,7758,Male,White,1999-05-05T00:00:00.000,...,550,NORTHWEST,D13,Forest Dennis,2465574.97950000000,7015317.48800000000,"{'latitude': '32.903019', 'longitude': '-96.88...",13,19367,3162
23,600,UF2013-00726,2145,2800 S MALCOLM X BLVD,2013-01-12T00:00:00.000,20:50,10214,Male,Hispanic,2010-06-09T00:00:00.000,...,340,SOUTHEAST,D7,JuliusSchepps Central,2500049.70336000000,6967767.58024000000,"{'human_address': '{""address"": ""2800 S MALCOLM...",NaN,NaN,NaN
24,612,UF2013-00749,4544,8100 SCYENE RD,2013-02-28T00:00:00.000,1:44,9370,Male,White,2008-02-06T00:00:00.000,...,320,SOUTHEAST,D5,LakeJune Buckner,2527156.61141000000,6965474.64845000000,"{'latitude': '32.763361', 'longitude': '-96.68...",5,19359,3162
25,626,UF2013-00780,"4888, 4889",S LOOP 12 ACRD N,2013-03-13T00:00:00.000,22:00,9677,Female,White,2008-12-10T00:00:00.000,...,730,SOUTH CENTRAL,D4,NaN,2505281.52491000000,6943012.44764000000,"{'human_address': '{""address"": ""S LOOP 12 ACRD...",NaN,NaN,NaN
26,619,UF2013-00768,10177,4626 REIGER AVE,2013-01-16T00:00:00.000,12:10,8370,Male,Black,2003-04-25T00:00:00.000,...,110,CENTRAL,D2,Ross Bennett,2500802.07484000000,6976150.25448000000,"{'latitude': '32.794441', 'longitude': '-96.76...",2,20160,3162
27,638,UF2013-00796,5198,723 JONELLE AVE,2013-03-24T00:00:00.000,19:00,10142,Male,White,2010-03-03T00:00:00.000,...,330,SOUTHEAST,D5,NaN,2519219.12974000000,6951424.40875000000,"{'latitude': '32.725265', 'longitude': '-96.70...",5,18921,3162
28,643,UF2013-00802,"14581, 14582",9524 MILITARY PKWY,2013-03-27T00:00:00.000,11:00,8450,Male,Hispanic,2000-01-12T00:00:00.000,...,320,SOUTHEAST,D7,StAugustine Bruton,2534252.74802000000,6967401.91595000000,"{'latitude': '32.768313', 'longitude': '-96.65...",7,19359,3162
29,671,UF2013-00821,5503,3068 FOREST LN,2013-03-30T00:00:00.000,23:20,9852,Male,White,2009-06-10T00:00:00.000,...,550,NORTHWEST,D13,Forest Dennis,2467385.79024000000,7017708.64797000000,"{'latitude': '32.90963', 'longitude': '-96.873...",13,19367,3162

In [80]:
df_2013[['match_addr','address']]

                    match_addr                        address
0        4600 S MALCOLM X BLVD         4600 S MALCOLM X Blvd.
1        4600 S MALCOLM X BLVD         4600 S Malcolm X Blvd.
2          3839 S FITZHUGH AVE           3839 S Fitzhugh Ave.
3     1700 S CESAR CHAVEZ BLVD        1700 CESAR CHAVEZ Blvd.
4            8300 L B J SERV S  8300 W LBJ service road Frwy.
...                        ...                            ...
4216          3700 GUARANTY ST              3700 Guaranty St.
4217     5900 HARRY HINES BLVD        5900 Harry Hines  Blvd.
4218       9500 WEBB CHAPEL RD           9500 WEBB CHAPEL Rd.
4219       9100 N CENTRAL EXPY          9100 N CENTRAL Expwy.
4220     9700 HARRY HINES BLVD        9700 S HARRYHINES Blvd.

[4221 rows x 2 columns]

In [81]:
df_2013.drop(['address'],axis=1,inplace=True)

In [82]:
# rename columns
df_2013.rename(columns={'match_addr':'address','dist_name':'council_district','geolocation':'geocoded_column'},inplace=True)

In [83]:
# replace NaN string values with None type for proper load into database
df_2013.replace(to_replace='NaN',inplace=True)

objectid                       None
filenum                        None
uofnum                         None
address                        None
occurred_d                     None
occurred_t                     None
current_ba                     None
offsex                         None
offrace                        None
hire_dt                        None
off_injure                     None
offcondtyp                     None
off_hospit                     None
service_ty                     None
forcetype                      None
uof_reason                     None
cycles_num                     None
forceeffec                     None
street_n                       None
street                         None
street_g                       None
street_t                       None
citnum                         None
citrace                        None
citsex                         None
cit_injure                     None
citcondtyp                     None
cit_arrest                     None
cit_infl_a                     None
citcharget                     None
ra                             None
beat                           None
sector                         None
division                       None
council_district               None
taag_name                      None
x                              None
y                              None
geocoded_column                None
:@computed_region_at43_7y52    None
:@computed_region_3qur_xvie    None
:@computed_region_28rh_izyk    None
dtype: object

In [84]:
# cast all empty values into None type
df_2013.where(pd.notnull(df_2013),None,inplace=True)

In [85]:
# convert the geocode column from dict to JSON string for load into database
df_2013['geocoded_column'] = df_2013['geocoded_column'].apply(lambda x:json.dumps(x))

In [86]:
# replace NULL string values with None type for proper load into database
df_2013.replace(to_replace='NULL',inplace=True)

objectid                       None
filenum                        None
uofnum                         None
address                        None
occurred_d                     None
occurred_t                     None
current_ba                     None
offsex                         None
offrace                        None
hire_dt                        None
off_injure                     None
offcondtyp                     None
off_hospit                     None
service_ty                     None
forcetype                      None
uof_reason                     None
cycles_num                     None
forceeffec                     None
street_n                       None
street                         None
street_g                       None
street_t                       None
citnum                         None
citrace                        None
citsex                         None
cit_injure                     None
citcondtyp                     None
cit_arrest                     None
cit_infl_a                     None
citcharget                     None
ra                             None
beat                           None
sector                         None
division                       None
council_district               None
taag_name                      None
x                              None
y                              None
geocoded_column                None
:@computed_region_at43_7y52    None
:@computed_region_3qur_xvie    None
:@computed_region_28rh_izyk    None
dtype: object

In [87]:
# adding the year reported values
df_2013['year_reported'] = '2013'

In [88]:
# load into table
df_2013[[item for item in table_cols if item in df_2013.columns]].to_sql('uof_filenum',engine,schema='cdep',if_exists='append',index=False,method='multi')

In [89]:
con.commit()
con.close()

- - -

## Experimental code for above

In [ ]:
df_2014.dropna(thresh=30)

In [ ]:
con.rollback() # for rolling back a failed transaction

In [ ]:
type(df_2019.geocoded_column[0])

In [ ]:
df_2019[df_2019['geocoded_column']=='NaN']

In [ ]:
json.dumps(df_2019['geocoded_column'][0])

In [ ]:
df_2019[['off_injure',
       'offcondtyp', 'off_hospit', 'service_ty', 'forcetype', 'uof_reason',
       'cycles_num', 'forceeffec', 'street_n', 'street', 'street_g',
       'street_t', 'address', 'citnum', 'citrace', 'citsex', 'cit_injure']]